/*
 * Copyright (c) 2012-2014 by Asiainfo Linkage
 * All rights reserved.
 * $Id: ESBInterFaceCode.java 656156 2016-08-28 07:17:35Z zhouqs $
 */
package com.crm.esb.invoke.intercode;

/**
 * ESB接口常量定义
 * @User: mayc
 * @Date: 2014年5月15日
 * @Time: 上午11:33:25
 * @version $Revision: 656156 $ $Date: 2016-08-28 15:17:35 +0800 (周日, 28 8月 2016) $
 */

public interface ESBInterFaceCode {
	
	String ESB_URL = "http://esb-ownchannel.yw.zj.chinamobile.com;";
	
    /**新版终端库存查询  @author mayc**/
    String SRV_ESB_RES_TMNL_TMNL_QRY_004 = "ESB_RES_TMNL_TMNL_QRY_004";
    String MN_ESB_RES_TMNL_TMNL_QRY_004 = ESB_URL+SRV_ESB_RES_TMNL_TMNL_QRY_004;
    
   /**终端信息信息查询  @author mayc**/
    String SRV_ESB_RES_TMNL_QRY_TMNLINFOQRY_001 ="ESB_RES_TMNL_QRY_TMNLINFOQRY_001";
    String MN_ESB_RES_TMNL_QRY_TMNLINFOQRY_001 = ESB_URL+SRV_ESB_RES_TMNL_QRY_TMNLINFOQRY_001;
    
    /**裸机业务办理  @author mayc**/
    String SRV_ESB_RES_TMNL_TMNL_SALE_002 ="ESB_RES_TMNL_TMNL_SALE_002";
    String MN_ESB_RES_TMNL_TMNL_SALE_002 = ESB_URL+SRV_ESB_RES_TMNL_TMNL_SALE_002;
    
    /**查询设备**/
    String SRV_ESB_SO_PERSONAL_ORDER_DEVICETYPEQRY_001 = "ESB_SO_PERSONAL_ORDER_DEVICETYPEQRY_001";
    String MN_ESB_SO_PERSONAL_ORDER_DEVICETYPEQRY_001= ESB_URL + SRV_ESB_SO_PERSONAL_ORDER_DEVICETYPEQRY_001;
    
    /**裸机活动销售接口 @author mayc **/
    String SRV_ESB_RES_TMNL_TMNL_SALE_001 ="ESB_RES_TMNL_TMNL_SALE_001";
    String MN_ESB_RES_TMNL_TMNL_SALE_001 = ESB_URL+SRV_ESB_RES_TMNL_TMNL_SALE_001;
    
    /**根据IMEI号进行常态裸机销售  @author mayc **/
    String SRV_ESB_RES_TMNL_TMNL_SALE_004 ="ESB_RES_TMNL_TMNL_SALE_004";
    String MN_ESB_RES_TMNL_TMNL_SALE_004 = ESB_URL+SRV_ESB_RES_TMNL_TMNL_SALE_004;
    
    /**资源类别型号查询 @author mayc**/
    String SRV_ESB_RES_RES_QRY_SPECQRY_001="ESB_RES_RES_QRY_SPECQRY_001";
    String MN_ESB_RES_RES_QRY_SPECQRY_001 =ESB_URL+SRV_ESB_RES_RES_QRY_SPECQRY_001;
    
    
    /**号码查询 @author liangjun**/
    String SRV_ESB_RES_NUM_NUM_QRY_002 ="ESB_RES_NUM_NUM_QRY_002";
    String MN_ESB_RES_NUM_NUM_QRY_002 =ESB_URL+SRV_ESB_RES_NUM_NUM_QRY_002;
    
    /**客户信息查询（三户查询）@author mayc**/
    String SRV_ESB_CS_QRY_MULTI_MULTIQRY_001 ="ESB_CS_QRY_MULTI_MULTIQRY_001";
    String MN_ESB_CS_QRY_MULTI_MULTIQRY_001 =ESB_URL+SRV_ESB_CS_QRY_MULTI_MULTIQRY_001;
    
    /**用户综合信息查询@author bijun**/
    String SRV_ESB_CS_QRY_MULTI_MULTIQRY_016 ="ESB_CS_QRY_MULTI_MULTIQRY_016";
    String MN_ESB_CS_QRY_MULTI_MULTIQRY_016 =ESB_URL+SRV_ESB_CS_QRY_MULTI_MULTIQRY_016;
    
    /**用户信息认证@author mayc**/
    String SRV_ESB_BASE_AUTH_AUTH_PWD_002 = "ESB_BASE_AUTH_AUTH_PWD_002";
    String MN_ESB_BASE_AUTH_AUTH_PWD_002 =ESB_URL+SRV_ESB_BASE_AUTH_AUTH_PWD_002;
    
    /**有线宽带预受理提交@author hujian3**/
    String SRV_ESB_SO_PERSONAL_VAS_ORDER_009 = "ESB_SO_PERSONAL_VAS_ORDER_009";
    String MN_ESB_SO_PERSONAL_VAS_ORDER_009 =ESB_URL+SRV_ESB_SO_PERSONAL_VAS_ORDER_009;
    
    /**校验户主或成员-有线宽带预受理@author hujian3**/
    String SRV_ESB_SO_PERSONAL_ORDER_CHECK_004 = "ESB_SO_PERSONAL_ORDER_CHECK_004";
    String MN_ESB_SO_PERSONAL_ORDER_CHECK_004 =ESB_URL+SRV_ESB_SO_PERSONAL_ORDER_CHECK_004;
    
    /**用户账户余额查询@author mayc**/
    String SRV_ESB_CS_QRY_RESULT_BAL_001 ="ESB_CS_QRY_RESULT_BAL_001";
    String MN_ESB_CS_QRY_RESULT_BAL_001 =ESB_URL+SRV_ESB_CS_QRY_RESULT_BAL_001;
    
    /**用户策划订购信息查询@author xiesb**/
    String SRV_ESB_CS_QRY_MULTI_MULTIQRY_012 ="ESB_CS_QRY_MULTI_MULTIQRY_012";
    String MN_ESB_CS_QRY_MULTI_MULTIQRY_012 =ESB_URL+SRV_ESB_CS_QRY_MULTI_MULTIQRY_012;
    
    /**操作员密码修改 @author bijun**/
    String SRV_ESB_BASE_SEC_OPER_UPDATE_001 = "ESB_BASE_SEC_OPER_UPDATE_001";
    String MN_ESB_BASE_SEC_OPER_UPDATE_001 = ESB_URL+SRV_ESB_BASE_SEC_OPER_UPDATE_001;
    
    /**短信发送 @author bijun**/
    String SRV_ESB_BASE_SMS_PUSH_PUSH_001 = "ESB_BASE_SMS_PUSH_PUSH_001";
    String MN_ESB_BASE_SMS_PUSH_PUSH_001 = ESB_URL+SRV_ESB_BASE_SMS_PUSH_PUSH_001;
    
    /**实物兑换规则@author zhengyx5**/
    String SRV_ESB_PROD_PROD_QRY_RULE_001 = "ESB_PROD_PROD_QRY_RULE_001";
    String MN_ESB_PROD_PROD_QRY_RULE_001 = ESB_URL+SRV_ESB_PROD_PROD_QRY_RULE_001;
    
    /**亲情网查询@author zhengyx5**/
    String SRV_ESB_SO_PERSONAL_FN_QRY_002 = "ESB_SO_PERSONAL_FN_QRY_002";
    String MN_ESB_SO_PERSONAL_FN_QRY_002 = ESB_URL+SRV_ESB_SO_PERSONAL_FN_QRY_002;
      
    /**亲情网组网@author zhengyx5**/
    String SRV_ESB_SO_PERSONAL_FN_CREATE_002 = "ESB_SO_PERSONAL_FN_CREATE_002";
    String MN_ESB_SO_PERSONAL_FN_CREATE_002 = ESB_URL+SRV_ESB_SO_PERSONAL_FN_CREATE_002;
    
    /**亲情网拆网@author zhengyx5**/
    String SRV_ESB_SO_PERSONAL_FN_REMOVE_001 = "ESB_SO_PERSONAL_FN_REMOVE_001";
    String MN_ESB_SO_PERSONAL_FN_REMOVE_001 = ESB_URL+SRV_ESB_SO_PERSONAL_FN_REMOVE_001;
    
    /**亲情网成员变更@author zhengyx5**/
    String SRV_ESB_SO_PERSONAL_FN_CHANGE_003 = "ESB_SO_PERSONAL_FN_CHANGE_003";
    String MN_ESB_SO_PERSONAL_FN_CHANGE_003 = ESB_URL+SRV_ESB_SO_PERSONAL_FN_CHANGE_003;
    
    /**亲情网升降级@author zhengyx5**/
    String SRV_ESB_SO_PERSONAL_FN_CHANGE_002 = "ESB_SO_PERSONAL_FN_CHANGE_002";
    String MN_ESB_SO_PERSONAL_FN_CHANGE_002 = ESB_URL+SRV_ESB_SO_PERSONAL_FN_CHANGE_002;
    
    /**套餐变更模拟月费信息**/
	String SRV_ESB_CS_QRY_OTHER_OFFERFEE_001 = "ESB_CS_QRY_OTHER_OFFERFEE_001";
	String MN_ESB_CS_QRY_OTHER_OFFERFEE_001 = ESB_URL+SRV_ESB_CS_QRY_OTHER_OFFERFEE_001;
    
    /**亲情网短信畅发@author zhengyx5**/
    String SRV_ESB_SO_PERSONAL_FN_CHANGE_007 = "ESB_SO_PERSONAL_FN_CHANGE_007";
    String MN_ESB_SO_PERSONAL_FN_CHANGE_007 = ESB_URL+SRV_ESB_SO_PERSONAL_FN_CHANGE_007;
    
    /**实物退换货查询@author zhengyx5**/
    String SRV_ESB_RES_ENTITY_EXCHG_QRY_001 = "ESB_RES_ENTITY_EXCHG_QRY_001";
    String MN_ESB_RES_ENTITY_EXCHG_QRY_001 = ESB_URL+SRV_ESB_RES_ENTITY_EXCHG_QRY_001;
     
    /**实物退换货受理@author zhengyx5**/
    String SRV_ESB_RES_ENTITY_STOCK_INOUT_013 = "ESB_RES_ENTITY_STOCK_INOUT_013";
    String MN_ESB_RES_ENTITY_STOCK_INOUT_013 = ESB_URL+SRV_ESB_RES_ENTITY_STOCK_INOUT_013;
    
    /**宽带预约查询@author dongjf**/
    String SRV_ESB_SO_PERSONAL_WB_PREORDER_001 = "ESB_SO_PERSONAL_WB_PREORDER_001";
    String MN_ESB_SO_PERSONAL_WB_PREORDER_001 = ESB_URL+SRV_ESB_SO_PERSONAL_WB_PREORDER_001;
    
    /**虚拟网资费查询@author dongjf**/
    String SRV_ESB_SO_GROUP_VPMN_QRY_003 = "ESB_SO_GROUP_VPMN_QRY_003";
    String MN_ESB_SO_GROUP_VPMN_QRY_003 = ESB_URL+SRV_ESB_SO_GROUP_VPMN_QRY_003;
    
    /**虚拟网短号查询@author dongjf**/
    String SRV_ESB_SO_GROUP_VPMN_QRY_007 = "ESB_SO_GROUP_VPMN_QRY_007";
    String MN_ESB_SO_GROUP_VPMN_QRY_007 = ESB_URL+SRV_ESB_SO_GROUP_VPMN_QRY_007;
    
    /**虚拟网根据手机号码查询@author dongjf**/
	String SRV_ESB_SO_GROUP_VPMN_QRY_001 = "ESB_SO_GROUP_VPMN_QRY_001";
    String MN_ESB_SO_GROUP_VPMN_QRY_001 = ESB_URL+SRV_ESB_SO_GROUP_VPMN_QRY_001;
    
    /**虚拟网根据名称查询@author dongjf**/
    String SRV_ESB_SO_GROUP_VPMN_QRY_008 = "ESB_SO_GROUP_VPMN_QRY_008";
    String MN_ESB_SO_GROUP_VPMN_QRY_008 = ESB_URL+SRV_ESB_SO_GROUP_VPMN_QRY_008;
    
    /**虚拟网办理更新@author dongjf**/
    String SRV_ESB_SO_GROUP_VPMN_CHANGE_001 = "ESB_SO_GROUP_VPMN_CHANGE_001";
    String MN_ESB_SO_GROUP_VPMN_CHANGE_001 = ESB_URL+SRV_ESB_SO_GROUP_VPMN_CHANGE_001;
    
    /**虚拟网添加@author dongjf**/
    String SRV_ESB_SO_GROUP_VPMN_ADD_001 = "ESB_SO_GROUP_VPMN_ADD_001";
    String MN_ESB_SO_GROUP_VPMN_ADD_001 = ESB_URL+SRV_ESB_SO_GROUP_VPMN_ADD_001;
    
    /**虚拟网退出@author dongjf**/
    String SRV_ESB_SO_GROUP_VPMN_DELETE_001 = "ESB_SO_GROUP_VPMN_DELETE_001";
    String MN_ESB_SO_GROUP_VPMN_DELETE_001 = ESB_URL+SRV_ESB_SO_GROUP_VPMN_DELETE_001;
    
    /**虚拟网本月是否退出@author dongjf**/
	String SRV_ESB_SO_GROUP_VPMN_QRY_005 = "ESB_SO_GROUP_VPMN_QRY_005";
    String MN_ESB_SO_GROUP_VPMN_QRY_005 = ESB_URL+SRV_ESB_SO_GROUP_VPMN_QRY_005;
    
    /**业务规则预判服务@author dongjf**/
    String SRV_ESB_RULE_PRECHK_BUSIOPER_001 = "ESB_BASE_RULE_BUSIRULE_CHK_002";
    String MN_ESB_RULE_PRECHK_BUSIOPER_001 = ESB_URL+SRV_ESB_RULE_PRECHK_BUSIOPER_001;
    
    /**指定规则校验服务@author dongjf**/
    String SRV_ESB_RULE_PRECHK_POINT_RULE_001 = "ESB_BASE_RULE_BUSIRULE_CHK_001";
    String MN_ESB_RULE_PRECHK_POINT_RULE_001 = ESB_URL+SRV_ESB_RULE_PRECHK_POINT_RULE_001;
    
    /**规则清单查询服务@author dongjf**/
    String SRV_ESB_RULE_QRY_RULE_LIST_001 = "ESB_BASE_RULE_BUSIRULE_QRY_001";
    String MN_ESB_RULE_QRY_RULE_LIST_001 = ESB_URL+SRV_ESB_RULE_QRY_RULE_LIST_001;
    
    /**用户补卡免费次数查询@author bijun**/
    String SRV_ESB_CS_SC_SC_FREECHGQRY_001 = "ESB_CS_SC_SC_FREECHGQRY_001";
    String MN_ESB_CS_SC_SC_FREECHGQRY_001 = ESB_URL+SRV_ESB_CS_SC_SC_FREECHGQRY_001;
    
    /**用户补换卡@author bijun**/
    String SRV_ESB_CS_SC_SC_CHANGECARD_002 = "ESB_CS_SC_SC_CHANGECARD_002";
    String MN_ESB_CS_SC_SC_CHANGECARD_002 = ESB_URL+SRV_ESB_CS_SC_SC_CHANGECARD_002;
    
    
    /**账户信息查询@author yangr**/
    String SRV_ESB_CS_QRY_MULTI_MULTIQRY_002 = "ESB_CS_QRY_MULTI_MULTIQRY_002";
    String MN_ESB_CS_QRY_MULTI_MULTIQRY_002 = ESB_URL+SRV_ESB_CS_QRY_MULTI_MULTIQRY_002;
    
    /**个性化账单查询@author yangr**/
    String SRV_ESB_CM_AM_AM_CUSTOMBILLQRY_001 = "ESB_CM_AM_AM_CUSTOMBILLQRY_001";
    String MN_ESB_CM_AM_AM_CUSTOMBILLQRY_001 = ESB_URL+SRV_ESB_CM_AM_AM_CUSTOMBILLQRY_001;
    
    
    /**过户提交@author yangr**/
    String SRV_ESB_CS_SC_TRANSUSER_ORDER_001 = "ESB_CS_SC_TRANSUSER_ORDER_001";
    String MN_ESB_CS_SC_TRANSUSER_ORDER_001 = ESB_URL+SRV_ESB_CS_SC_TRANSUSER_ORDER_001;
    
    
    /**统一支付查询@author yangr**/
    String SRV_ESB_CS_QRY_CM_ACCRELQRY_001 = "ESB_CS_QRY_CM_ACCRELQRY_001";
    String MN_ESB_CS_QRY_CM_ACCRELQRY_001 = ESB_URL+SRV_ESB_CS_QRY_CM_ACCRELQRY_001;
    
    /**统一支付组网@author yangr**/
    String SRV_ESB_SO_PERSONAL_UNIPAY_CREATE_001 = "ESB_SO_PERSONAL_UNIPAY_CREATE_001";
    String MN_ESB_SO_PERSONAL_UNIPAY_CREATE_001 = ESB_URL+SRV_ESB_SO_PERSONAL_UNIPAY_CREATE_001;
    
    /**统一支付拆网@author yangr**/
    String SRV_ESB_SO_PERSONAL_UNIPAY_CANCEL_001 = "ESB_SO_PERSONAL_UNIPAY_CANCEL_001";
    String MN_ESB_SO_PERSONAL_UNIPAY_CANCEL_001 = ESB_URL+SRV_ESB_SO_PERSONAL_UNIPAY_CANCEL_001;
    
    /**统一支付成员变更@author yangr**/
    String SRV_ESB_SO_PERSONAL_UNIPAY_CHANGE_001 = "ESB_SO_PERSONAL_UNIPAY_CHANGE_001";
    String MN_ESB_SO_PERSONAL_UNIPAY_CHANGE_001 = ESB_URL+SRV_ESB_SO_PERSONAL_UNIPAY_CHANGE_001;
    
    /**过户查询老经办人信息@author yangr**/
    String SRV_ESB_CS_QRY_OTHER_HANDLERQRY_001 = "ESB_CS_QRY_OTHER_HANDLERQRY_001";
    String MN_ESB_CS_QRY_OTHER_HANDLERQRY_001 = ESB_URL+SRV_ESB_CS_QRY_OTHER_HANDLERQRY_001;
    
    /**SIM卡查询@author yangr**/
    String SRV_ESB_RES_SIM_SIM_QRY_003 = "ESB_RES_SIM_SIM_QRY_003";
    String MN_ESB_RES_SIM_SIM_QRY_003 = ESB_URL+SRV_ESB_RES_SIM_SIM_QRY_003;
    
    
    /**根据号码判断是否是优选号码@author yangr**/
    String SRV_ESB_RES_NUM_NUM_QRY_004 = "ESB_RES_NUM_NUM_QRY_004";
    String MN_ESB_RES_NUM_NUM_QRY_004 = ESB_URL+SRV_ESB_RES_NUM_NUM_QRY_004;
    
    /**根据号码判断是否是优选号码(ESB换了新接口)@author bijun**/
    String SRV_ESB_RES_NUM_BILL_QRY_001 = "ESB_RES_NUM_BILL_QRY_001";
    String MN_ESB_RES_NUM_BILL_QRY_001 = ESB_URL+SRV_ESB_RES_NUM_BILL_QRY_001;
    
    /**免填单打印记录查询@author xiesb**/
    String SRV_ESB_BASE_PRINT_BUSIPRINT_RECORDQRY_001 ="ESB_BASE_PRINT_BUSIPRINT_RECORDQRY_001";
    String MN_ESB_BASE_PRINT_BUSIPRINT_RECORDQRY_001 =ESB_URL+SRV_ESB_BASE_PRINT_BUSIPRINT_RECORDQRY_001;
    
    /**免填单打印内容查询@author xiesb**/
    String SRV_ESB_BASE_PRINT_BUSIPRINT_CONTENTQRY_001 ="ESB_BASE_PRINT_BUSIPRINT_CONTENTQRY_001";
    String MN_ESB_BASE_PRINT_BUSIPRINT_CONTENTQRY_001 =ESB_URL+SRV_ESB_BASE_PRINT_BUSIPRINT_CONTENTQRY_001;
    
    /**更新免填单打印信息@author xiesb**/
    String SRV_ESB_BASE_PRINT_BUSIPRINT_CONTENTCHG_001 ="ESB_BASE_PRINT_BUSIPRINT_CONTENTCHG_001";
    String MN_ESB_BASE_PRINT_BUSIPRINT_CONTENTCHG_001 =ESB_URL+SRV_ESB_BASE_PRINT_BUSIPRINT_CONTENTCHG_001;

    /**查询SIM卡信息@author bijun**/
    String SRV_ESB_RES_SIM_SIM_QRY_001 = "ESB_RES_SIM_SIM_QRY_001";
    String MN_ESB_RES_SIM_SIM_QRY_001 = ESB_URL+SRV_ESB_RES_SIM_SIM_QRY_001;
    
    
    /**免费资源使用量查询@author mayc on 2014-07-04**/
    String SRV_ESB_CS_QRY_USED_FREERES_001 = "ESB_CS_QRY_USED_FREERES_001";
    String MN_ESB_CS_QRY_USED_FREERES_001 = ESB_URL+SRV_ESB_CS_QRY_USED_FREERES_001;

    /**查询证件下所有用户@author dongjf on 2014-07-06**/
	String SRV_ESB_CS_QRY_MULTI_MULTIQRY_003 = "ESB_CS_QRY_MULTI_MULTIQRY_003";
	String MN_ESB_CS_QRY_MULTI_MULTIQRY_003 = ESB_URL+SRV_ESB_CS_QRY_MULTI_MULTIQRY_003;
	
	/** 查询账号下所有用户@author dongjf on 2014-07-06 **/
	String SRV_ESB_CS_QRY_MULTI_MULTIQRY_014 = "ESB_CS_QRY_MULTI_MULTIQRY_014";
	String MN_ESB_CS_QRY_MULTI_MULTIQRY_014 = ESB_URL + SRV_ESB_CS_QRY_MULTI_MULTIQRY_014;

	 /**查询客户是否为黑名单@author yangrui on 2014-07-08**/
	String SRV_ESB_CS_QRY_CM_CUSTOMQRY_012 = "ESB_CS_QRY_CM_CUSTOMQRY_012";
	String MN_ESB_CS_QRY_CM_CUSTOMQRY_012 = ESB_URL+SRV_ESB_CS_QRY_CM_CUSTOMQRY_012;
	

	/**客户实名资料补录或登 记@author xiesb**/
    String SRV_ESB_CM_CM_CM_CHANGE_004 = "ESB_CM_CM_CM_CHANGE_004";
    String MN_ESB_CM_CM_CM_CHANGE_004 = ESB_URL+SRV_ESB_CM_CM_CM_CHANGE_004;
    
    /**查询用户VIP信息@author zhengyx5 on 2014-07-07**/
	String SRV_ESB_CS_QRY_OTHER_VIP_001 = "ESB_CS_QRY_OTHER_VIP_001";
	String MN_ESB_CS_QRY_OTHER_VIP_001 = ESB_URL+SRV_ESB_CS_QRY_OTHER_VIP_001;
	
	/**用户联系人查询@author zhengyx5 on 2014-07-07**/
	String SRV_ESB_CS_DM_CONTACT_QRY_001 = "ESB_CS_DM_CONTACT_QRY_001";
	String MN_ESB_CS_DM_CONTACT_QRY_001 = ESB_URL+SRV_ESB_CS_DM_CONTACT_QRY_001;
	
	/**用户联系人查询@author xianan on 2014-11-07**/
	String SRV_ESB_CS_DM_CONTACT_QRY_002 = "ESB_CS_DM_CONTACT_QRY_002";
	String MN_ESB_CS_DM_CONTACT_QRY_002 = ESB_URL+SRV_ESB_CS_DM_CONTACT_QRY_002;
	
	/**用户预缴信息查询@author bijun on 2014-07-08**/
	String SRV_ESB_SO_PERSONAL_PREPAY_QRY_001 = "ESB_SO_PERSONAL_PREPAY_QRY_001";
	String MN_ESB_SO_PERSONAL_PREPAY_QRY_001 = ESB_URL+SRV_ESB_SO_PERSONAL_PREPAY_QRY_001;
	
	/**促销信息查询@author bijun on 2014-07-08**/
	String SRV_ESB_CS_QRY_ORDER_INSQRY_013 = "ESB_CS_QRY_ORDER_INSQRY_013";
	String MN_ESB_CS_QRY_ORDER_INSQRY_013 = ESB_URL+SRV_ESB_CS_QRY_ORDER_INSQRY_013;
	
	/**终端捆绑信息查询@author bijun on 2014-07-08**/
	String SRV_ESB_RES_TMNL_BIND_QRY_001 = "ESB_RES_TMNL_BIND_QRY_001";
	String MN_ESB_RES_TMNL_BIND_QRY_001 = ESB_URL+SRV_ESB_RES_TMNL_BIND_QRY_001;
	
	/**机卡分离信息查询@author bijun on 2014-07-10**/
	String SRV_ESB_SO_PERSONAL_TB_QRY_001 = "ESB_SO_PERSONAL_TB_QRY_001";
	String MN_ESB_SO_PERSONAL_TB_QRY_001 = ESB_URL+SRV_ESB_SO_PERSONAL_TB_QRY_001;
	
	/**外省客户查询@author mayc on 2014-07-08**/
	String SRV_ESB_CS_QRY_MULTI_MULTIQRY_013 = "ESB_CS_QRY_MULTI_MULTIQRY_013";
	String MN_ESB_CS_QRY_MULTI_MULTIQRY_013 = ESB_URL+SRV_ESB_CS_QRY_MULTI_MULTIQRY_013;

	
	/**查询宽带用户信息@author zhengyx5 on 2014-07-07**/
	String SRV_ESB_SO_PERSONAL_WB_QRY_001 = "ESB_SO_PERSONAL_WB_QRY_001";
	String MN_ESB_SO_PERSONAL_WB_QRY_001 = ESB_URL+SRV_ESB_SO_PERSONAL_WB_QRY_001;
	
	/**查询用户信用度@author zhengyx5 on 2014-07-07**/
	String SRV_ESB_CS_QRY_ORDER_INSQRY_025 = "ESB_CS_QRY_ORDER_INSQRY_025";
	String MN_ESB_CS_QRY_ORDER_INSQRY_025 = ESB_URL+SRV_ESB_CS_QRY_ORDER_INSQRY_025;

	/**用户保底信息查询@author mayc on 2014-07-08**/
	String SRV_ESB_CS_QRY_MULTI_MULTIQRY_015 = "ESB_CS_QRY_MULTI_MULTIQRY_015";
	String MN_ESB_CS_QRY_MULTI_MULTIQRY_015 = ESB_URL+SRV_ESB_CS_QRY_MULTI_MULTIQRY_015;

	/**查询用户月账单信息@author mayc on 2014-07-08**/
	String SRV_ESB_CS_QRY_RECORD_MULTIBILL_001 = "ESB_CS_QRY_RECORD_MULTIBILL_001";
	String MN_ESB_CS_QRY_RECORD_MULTIBILL_001 = ESB_URL+SRV_ESB_CS_QRY_RECORD_MULTIBILL_001;
	
	/**用户预占号码查询@author hujian3**/
    String SRV_ESB_RES_NUM_NUM_QRY_005 = "ESB_RES_NUM_NUM_QRY_005";
    String MN_ESB_RES_NUM_NUM_QRY_005 = ESB_URL+SRV_ESB_RES_NUM_NUM_QRY_005;
    
	/**用户预约号码查询@author jinming on 2016-01-19**/
    String SRV_ESB_RES_NUM_NUM_QRY_007 = "ESB_RES_NUM_NUM_QRY_007";
    String MN_ESB_RES_NUM_NUM_QRY_007 = ESB_URL+SRV_ESB_RES_NUM_NUM_QRY_007;
    
    /**号码来源查询@author hujian3**/
    String SRV_ESB_RES_NUM_QRY_003 = "ESB_RES_NUM_QRY_003";
    String MN_ESB_RES_NUM_QRY_003 = ESB_URL+SRV_ESB_RES_NUM_QRY_003;
    
    /**可选号码查询@author hujian3**/
    String SRV_ESB_RES_NUM_NUM_QRY_003 = "ESB_RES_NUM_NUM_QRY_003";
    String MN_ESB_RES_NUM_NUM_QRY_003 = ESB_URL+SRV_ESB_RES_NUM_NUM_QRY_003;
    
    /**号码预占@author hujian3**/
    String SRV_ESB_RES_NUM_OPER_001 = "ESB_RES_NUM_OPER_001";
    String MN_ESB_RES_NUM_OPER_001 = ESB_URL+SRV_ESB_RES_NUM_OPER_001;

    /**用户群组信息查询@author mayc on 2014-07-08**/
	String SRV_ESB_SO_PERSONAL_GRP_QRY_001 = "ESB_SO_PERSONAL_GRP_QRY_001";
	String MN_ESB_SO_PERSONAL_GRP_QRY_001 = ESB_URL+SRV_ESB_SO_PERSONAL_GRP_QRY_001;
	
	/**账务资金变化明细@author zhengyx5 on 2014-07-08**/
	String SRV_ESB_CS_QRY_ACC_QRY_002 = "ESB_CS_QRY_ACC_QRY_002";
	String MN_ESB_CS_QRY_ACC_QRY_002 = ESB_URL+SRV_ESB_CS_QRY_ACC_QRY_002;
	
	/**账务月销帐记录查询@author bijun on 2014-07-24**/
	String SRV_ESB_CS_QRY_ACC_QRY_003 = "ESB_CS_QRY_ACC_QRY_003";
	String MN_ESB_CS_QRY_ACC_QRY_003 = ESB_URL+SRV_ESB_CS_QRY_ACC_QRY_003;
	
	 /**sim卡手机号匹配校验@author hujian3 on 2014-07-14**/
    String SRV_ESB_RES_SIM_SIM_QRY_002 = "ESB_RES_SIM_SIM_QRY_002";
    String MN_ESB_RES_SIM_SIM_QRY_002 = ESB_URL+SRV_ESB_RES_SIM_SIM_QRY_002;
    
    /**计算策划生失效时间@author hujian3 on 2014-07-14**/
    String SRV_ESB_CS_QRY_ORDER_OTHERQRY_002 = "ESB_CS_QRY_ORDER_OTHERQRY_002";
    String MN_ESB_CS_QRY_ORDER_OTHERQRY_002 = ESB_URL+SRV_ESB_CS_QRY_ORDER_OTHERQRY_002;
    
    /**开户受理接口@author hujian3 on 2014-07-14**/
    String SRV_ESB_SO_PERSONAL_GSM_OPEN_003 = "ESB_SO_PERSONAL_GSM_OPEN_003";
    String MN_ESB_SO_PERSONAL_GSM_OPEN_003 = ESB_URL+SRV_ESB_SO_PERSONAL_GSM_OPEN_003;

    /**策划费用信息查询@author bijun on 2014-07-15**/
    String SRV_ESB_CS_QRY_FEE_OFFER_001 = "ESB_CS_QRY_FEE_OFFER_001";
    String MN_ESB_CS_QRY_FEE_OFFER_001 = ESB_URL+SRV_ESB_CS_QRY_FEE_OFFER_001;
    
    /**模糊认证问题查询@author yangrui on 2014-07-16**/
    String SRV_ESB_BASE_AUTH_FUZZY_QRY_001 = "ESB_BASE_AUTH_FUZZY_QRY_001";
    String MN_ESB_BASE_AUTH_FUZZY_QRY_001 = ESB_URL+SRV_ESB_BASE_AUTH_FUZZY_QRY_001;
    
    /**模糊认证参考答案查询@author yangrui on 2014-07-16**/
    String SRV_ESB_BASE_AUTH_FUZZY_QRY_002 = "ESB_BASE_AUTH_FUZZY_QRY_002";
    String MN_ESB_BASE_AUTH_FUZZY_QRY_002 = ESB_URL+SRV_ESB_BASE_AUTH_FUZZY_QRY_002;
    
    /**模糊认证答案提交@author yangrui on 2014-07-16**/
    String SRV_ESB_BASE_AUTH_FUZZY_VERIFY_001 = "ESB_BASE_AUTH_FUZZY_VERIFY_001";
    String MN_ESB_BASE_AUTH_FUZZY_VERIFY_001 = ESB_URL+SRV_ESB_BASE_AUTH_FUZZY_VERIFY_001;
    
    /**模糊认证问题验证@author yangrui on 2014-07-16**/
    String SRV_ESB_BASE_AUTH_FUZZY_VERIFY_002 = "ESB_BASE_AUTH_FUZZY_VERIFY_002";
    String MN_ESB_BASE_AUTH_FUZZY_VERIFY_002 = ESB_URL+SRV_ESB_BASE_AUTH_FUZZY_VERIFY_002;
    
    /**查询证件下所有客户@author yangrui on 2014-07-17**/
    String SRV_ESB_CS_QRY_MULTI_MULTIQRY_008 = "ESB_CS_QRY_MULTI_MULTIQRY_008";
    String MN_ESB_CS_QRY_MULTI_MULTIQRY_008 = ESB_URL+SRV_ESB_CS_QRY_MULTI_MULTIQRY_008;
    
    /**业务受理记录查询@author xiesb on 2014-07-21**/
	String SRV_ESB_CS_QRY_ORDER_BUSIQRY_001 = "ESB_CS_QRY_ORDER_BUSIQRY_001";
	String MN_ESB_CS_QRY_ORDER_BUSIQRY_001 = ESB_URL+SRV_ESB_CS_QRY_ORDER_BUSIQRY_001;
	
	 /**缴费卡充值@author yangrui on 2014-07-24**/
	String SRV_ESB_CS_AMS_FUND_CHARGE_003  = "ESB_CS_AMS_FUND_CHARGE_003";
	String MN_ESB_CS_AMS_FUND_CHARGE_003  = ESB_URL+SRV_ESB_CS_AMS_FUND_CHARGE_003;
	
	 /**现金充值@author yangrui on 2014-07-24**/
	String SRV_ESB_CS_AMS_FUND_CHARGE_008  = "ESB_CS_AMS_FUND_CHARGE_008";
	String MN_ESB_CS_AMS_FUND_CHARGE_008  = ESB_URL+SRV_ESB_CS_AMS_FUND_CHARGE_008;

	/**客户归属地查询@author mayc on 2014-07-28**/
	String SRV_ESB_CS_QRY_MULTI_MULTIQRY_011 = "ESB_CS_QRY_MULTI_MULTIQRY_011";
	String MN_ESB_CS_QRY_MULTI_MULTIQRY_011 = ESB_URL+SRV_ESB_CS_QRY_MULTI_MULTIQRY_011;
	
	/**订单产品变更信息查询@author xiesb on 2014-07-28**/
	String SRV_ESB_CS_QRY_ORDER_BUSIQRY_002 = "ESB_CS_QRY_ORDER_BUSIQRY_002";
	String MN_ESB_CS_QRY_ORDER_BUSIQRY_002 = ESB_URL+SRV_ESB_CS_QRY_ORDER_BUSIQRY_002;
	
	/*******************新接口增加在后面 **********************/
	
	/**用户策划费用信息查询@author bijun on 2014-07-29**/
	String SRV_ESB_SO_PERSONAL_OFFER_FEEQRY_001 = "ESB_SO_PERSONAL_OFFER_FEEQRY_001";
	String MN_ESB_SO_PERSONAL_OFFER_FEEQRY_001 = ESB_URL+SRV_ESB_SO_PERSONAL_OFFER_FEEQRY_001;
	
	/**模拟月费信息计算@author hujian3 on 2014-08-04**/
	String SRV_ESB_SO_PERSONAL_OFFER_FEECAL_001 = "ESB_SO_PERSONAL_OFFER_FEECAL_001";
	String MN_ESB_SO_PERSONAL_OFFER_FEECAL_001 = ESB_URL+SRV_ESB_SO_PERSONAL_OFFER_FEECAL_001;
	
	/**产品免费资源查询@author hujian3 on 2014-08-04**/
	String SRV_ESB_SO_PERSONAL_OFFER_FREERESQRY_001 = "ESB_SO_PERSONAL_OFFER_FREERESQRY_001";
	String MN_ESB_SO_PERSONAL_OFFER_FREERESQRY_001 = ESB_URL+SRV_ESB_SO_PERSONAL_OFFER_FREERESQRY_001;
	
	/**渠道入网开户受理@author hujian3 on 2014-08-09**/
	String SRV_ESB_SO_PERSONAL_GSM_OPEN_001 = "ESB_SO_PERSONAL_GSM_OPEN_001";
	String MN_ESB_SO_PERSONAL_GSM_OPEN_001 = ESB_URL+SRV_ESB_SO_PERSONAL_GSM_OPEN_001;

	/**发票池余额查询@author mayc on 2014-08-11**/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_005  = "ESB_RES_NOTE_INVOICE_QRY_005";
	String MN_ESB_RES_NOTE_INVOICE_QRY_005 = ESB_URL +SRV_ESB_RES_NOTE_INVOICE_QRY_005 ;
	
	/**一次性发票信息查询@author mayc on 2014-08-11**/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_003 = "ESB_RES_NOTE_INVOICE_QRY_003";
	String MN_ESB_RES_NOTE_INVOICE_QRY_003 = ESB_URL + SRV_ESB_RES_NOTE_INVOICE_QRY_003;
	
	/**营销案受理@author hujian3 on 2014-08-12**/
	String SRV_ESB_SO_PERSONAL_MCASE_ORDER_011 = "ESB_SO_PERSONAL_MCASE_ORDER_011";
	String MN_ESB_SO_PERSONAL_MCASE_ORDER_011 = ESB_URL + SRV_ESB_SO_PERSONAL_MCASE_ORDER_011;
	
	/**营销案换套餐受理@author hujian3 on 2014-08-12**/
	String SRV_ESB_SO_PERSONAL_GSM_CHANGE_001 = "ESB_SO_PERSONAL_GSM_CHANGE_001";
	String MN_ESB_SO_PERSONAL_GSM_CHANGE_001 = ESB_URL + SRV_ESB_SO_PERSONAL_GSM_CHANGE_001;

	/**年度积分查询@author bijun on 2014-08-12**/
	String SRV_ESB_CS_SCORE_SCORE_QRY_002 = "ESB_CS_SCORE_SCORE_QRY_002";
	String MN_ESB_CS_SCORE_SCORE_QRY_002 = ESB_URL + SRV_ESB_CS_SCORE_SCORE_QRY_002;
	
	/**国际长途漫游业务判断@author hujian3 on 2014-08-13**/
	String SRV_ESB_SO_PERSONAL_ORDER_CHECK_006 = "ESB_SO_PERSONAL_ORDER_CHECK_006";
	String MN_ESB_SO_PERSONAL_ORDER_CHECK_006 = ESB_URL + SRV_ESB_SO_PERSONAL_ORDER_CHECK_006;

	/**操作员发票信息查询@author mayc on 2014-08-15**/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_002 = "ESB_RES_NOTE_INVOICE_QRY_002";
	String MN_ESB_RES_NOTE_INVOICE_QRY_002 = ESB_URL + SRV_ESB_RES_NOTE_INVOICE_QRY_002;
	
	/**账单发票信息查询@author bijun on 2014-08-18**/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_004 = "ESB_RES_NOTE_INVOICE_QRY_004";
	String MN_ESB_RES_NOTE_INVOICE_QRY_004 = ESB_URL + SRV_ESB_RES_NOTE_INVOICE_QRY_004;
	
	/**流量升档查询@author hujian3 on 2014-08-19**/
	String SRV_ESB_SO_PERSONAL_FLOWUPSHIFT_QRY_001 = "ESB_SO_PERSONAL_FLOWUPSHIFT_QRY_001";
	String MN_ESB_SO_PERSONAL_FLOWUPSHIFT_QRY_001 = ESB_URL + SRV_ESB_SO_PERSONAL_FLOWUPSHIFT_QRY_001;

	/**自定义发票打印票据项目信息查询@author mayc on 2014-08-20**/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_007 = "ESB_RES_NOTE_INVOICE_QRY_007";
	String MN_ESB_RES_NOTE_INVOICE_QRY_007 = ESB_URL +SRV_ESB_RES_NOTE_INVOICE_QRY_007 ;

	/**纳税人信息查询@author mayc on 2014-08-25**/
	String SRV_ESB_CS_QRY_CM_CUSTOMQRY_002 = "ESB_CS_QRY_CM_CUSTOMQRY_002";
	String MN_ESB_CS_QRY_CM_CUSTOMQRY_002 = ESB_URL + SRV_ESB_CS_QRY_CM_CUSTOMQRY_002;
	
	/**充值缴费发票打印信息查询@author mayc on 2014-08-26**/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_001 = "ESB_RES_NOTE_INVOICE_QRY_001";
	String MN_ESB_RES_NOTE_INVOICE_QRY_001 = ESB_URL + SRV_ESB_RES_NOTE_INVOICE_QRY_001;

	/**账单发票打印内容获取@author bijun on 2014-08-28**/
	String SRV_ESB_RES_NOTE_INVOICE_PRINT_001 = "ESB_RES_NOTE_INVOICE_PRINT_001";
	String MN_ESB_RES_NOTE_INVOICE_PRINT_001 = ESB_URL + SRV_ESB_RES_NOTE_INVOICE_PRINT_001;
	
	/**客户关键资料变更@author bijun on 2014-08-28**/
	String SRV_ESB_CM_CM_CM_CHANGE_003 = "ESB_CM_CM_CM_CHANGE_003";
	String MN_ESB_CM_CM_CM_CHANGE_003 = ESB_URL + SRV_ESB_CM_CM_CM_CHANGE_003;
	
	/**常规资料变更@author dongjf on 2014-08-29**/
	String SRV_ESB_CM_CM_CM_CHANGE_002 = "ESB_CM_CM_CM_CHANGE_002";
	String MN_ESB_CM_CM_CM_CHANGE_002 = ESB_URL + SRV_ESB_CM_CM_CM_CHANGE_002;
	
	/**用户基本套餐变更(非营销案)@author hujian3 on 2014-08-28**/
	String SRV_ESB_SO_PERSONAL_GSM_CHANGE_002 = "ESB_SO_PERSONAL_GSM_CHANGE_002";
	String MN_ESB_SO_PERSONAL_GSM_CHANGE_002 = ESB_URL + SRV_ESB_SO_PERSONAL_GSM_CHANGE_002;
	
	/**客户信息查询@author bijun on 2014-08-29**/
	String SRV_ESB_CS_QRY_MULTI_MULTIQRY_005 = "ESB_CS_QRY_MULTI_MULTIQRY_005";
	String MN_ESB_CS_QRY_MULTI_MULTIQRY_005 = ESB_URL + SRV_ESB_CS_QRY_MULTI_MULTIQRY_005;
	
	/**自定义发票打印@author mayc on 2014-08-29**/
	String SRV_ESB_RES_NOTE_INVOICE_PRINT_002 = "ESB_RES_NOTE_INVOICE_PRINT_002";
	String MN_ESB_RES_NOTE_INVOICE_PRINT_002 = ESB_URL+SRV_ESB_RES_NOTE_INVOICE_PRINT_002;

	/**缴费发票打印@author mayc on 2014-08-29**/
	String SRV_ESB_RES_NOTE_INVOICE_PRINT_004 = "ESB_RES_NOTE_INVOICE_PRINT_004";
	String MN_ESB_RES_NOTE_INVOICE_PRINT_004 = ESB_URL + SRV_ESB_RES_NOTE_INVOICE_PRINT_004 ;
	
	/**一次性发票打印@author mayc on 2014-08-29**/
	String SRV_ESB_RES_NOTE_INVOICE_PRINT_003 = "ESB_RES_NOTE_INVOICE_PRINT_003";
	String MN_ESB_RES_NOTE_INVOICE_PRINT_003 = ESB_URL + SRV_ESB_RES_NOTE_INVOICE_PRINT_003;
	
	/**呼转受理@author YANGRUI on 2014-08-29**/
	String SRV_ESB_SO_PERSONAL_VAS_CHANGE_002 = "ESB_SO_PERSONAL_VAS_CHANGE_002";
	String MN_ESB_SO_PERSONAL_VAS_CHANGE_002 = ESB_URL +"ESB_SO_PERSONAL_VAS_CHANGE_002";
	
	/**发票打印记录查询@author Hc on 2014-08-27**/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_006="ESB_RES_NOTE_INVOICE_QRY_006";
	String MN_ESB_RES_NOTE_INVOICE_QRY_006 = ESB_URL + SRV_ESB_RES_NOTE_INVOICE_QRY_006;

	/**终端专票申请打印@author mayc on 2014-09-16**/
	String SRV_ESB_RES_NOTE_INVOICE_PRINT_007 = "ESB_RES_NOTE_INVOICE_PRINT_007";
	String MN_ESB_RES_NOTE_INVOICE_PRINT_007 = ESB_URL +SRV_ESB_RES_NOTE_INVOICE_PRINT_007 ;

	/**个性化帐单定制@author mayc on 2014-09-17**/
	String SRV_ESB_CM_AM_AM_CUSTOMBILLDEAL_001 = "ESB_CM_AM_AM_CUSTOMBILLDEAL_001";
	String MN_ESB_CM_AM_AM_CUSTOMBILLDEAL_001 = ESB_URL +SRV_ESB_CM_AM_AM_CUSTOMBILLDEAL_001;
	
	/**根据手机号码、推荐类型查询手机所在地市的个性化推荐信息 YANGRUI**/
	String SRV_ESB_SSM_CAMP_CAMP_RCM_001 = "ESB_SSM_CAMP_CAMP_RCM_001";
	String MN_ESB_SSM_CAMP_CAMP_RCM_001  = ESB_URL+SRV_ESB_SSM_CAMP_CAMP_RCM_001;
	
	/**历史欠费记录查询@author hj on 2014-09-15**/
	String SRV_ESB_CS_QRY_AMS_HISOWEQRY_001="ESB_CS_QRY_AMS_HISOWEQRY_001";
	String MN_ESB_CS_QRY_AMS_HISOWEQRY_001 = ESB_URL + SRV_ESB_CS_QRY_AMS_HISOWEQRY_001;
	
	/**报损账单信息查询@author hj on 2014-09-15**/
	String SRV_ESB_CS_QRY_AMS_LOSSBILLQRY_001="ESB_CS_QRY_AMS_LOSSBILLQRY_001";
	String MN_ESB_CS_QRY_AMS_LOSSBILLQRY_001 = ESB_URL + SRV_ESB_CS_QRY_AMS_LOSSBILLQRY_001;
	
	/**报损账单缴费@author hj on 2014-09-15**/
	String SRV_ESB_CS_AMS_FUND_CHARGE_009="ESB_CS_AMS_FUND_CHARGE_009";
	String MN_ESB_CS_AMS_FUND_CHARGE_009 = ESB_URL + SRV_ESB_CS_AMS_FUND_CHARGE_009;
	
	/**备卡查询*/
	String SRV_ESB_RES_SIM_BACKCARD_QRY_001 = "ESB_RES_SIM_BACKCARD_QRY_001";
	String MN_ESB_RES_SIM_BACKCARD_QRY_001 = ESB_URL + SRV_ESB_RES_SIM_BACKCARD_QRY_001;
	
	/**备卡维护*/
	String SRV_ESB_RES_SIM_BACKCARD_DEAL_001 = "ESB_RES_SIM_BACKCARD_DEAL_001";
	String MN_ESB_RES_SIM_BACKCARD_DEAL_001 = ESB_URL + SRV_ESB_RES_SIM_BACKCARD_DEAL_001;
	
	/**国际长途漫游押金查询@author hj on 2014-09-25**/
	String SRV_ESB_CS_QRY_FEE_LONGROAMQRY_001 = "ESB_CS_QRY_FEE_LONGROAMQRY_001";
	String MN_ESB_CS_QRY_FEE_LONGROAMQRY_001 = ESB_URL + SRV_ESB_CS_QRY_FEE_LONGROAMQRY_001;
	
	/** 月度积分查询*/
	String SRV_ESB_CS_SCORE_SCORE_QRY_001 = "ESB_CS_SCORE_SCORE_QRY_001";
	String MN_ESB_CS_SCORE_SCORE_QRY_001 = ESB_URL + SRV_ESB_CS_SCORE_SCORE_QRY_001;
	
	/** 积分兑换商品*/
	String SRV_ESB_CS_SCORE_SCORE_EXCHGRESQRY_001 = "ESB_CS_SCORE_SCORE_EXCHGRESQRY_001";
	String MN_ESB_CS_SCORE_SCORE_EXCHGRESQRY_001 = ESB_URL + SRV_ESB_CS_SCORE_SCORE_EXCHGRESQRY_001;
	
	/** 积分兑换*/
	String SRV_ESB_CS_SCORE_SCORE_EXCHANGE_001 = "ESB_CS_SCORE_SCORE_EXCHANGE_001";
	String MN_ESB_CS_SCORE_SCORE_EXCHANGE_001 = ESB_URL + SRV_ESB_CS_SCORE_SCORE_EXCHANGE_001;
	
	/** 积分返销记录查询*/
	String SRV_ESB_CS_SCORE_SCORE_QRY_004 = "ESB_CS_SCORE_SCORE_QRY_004";
	String MN_ESB_CS_SCORE_SCORE_QRY_004 = ESB_URL + SRV_ESB_CS_SCORE_SCORE_QRY_004;
	
	/** 积分返销订单查询*/
	String SRV_ESB_CS_SCORE_SCORE_ODRQRY_001 = "ESB_CS_SCORE_SCORE_ORDQRY_001";
	String MN_ESB_CS_SCORE_SCORE_ODRQRY_001 = ESB_URL + SRV_ESB_CS_SCORE_SCORE_ODRQRY_001;
	
	/** 积分过期积分查询 */
	String SRV_ESB_CS_SCORE_SCORE_QRY_005 = "ESB_CS_SCORE_SCORE_QRY_005";
	String MN_ESB_CS_SCORE_SCORE_QRY_005 = ESB_URL + SRV_ESB_CS_SCORE_SCORE_QRY_005;
	
	/** 积分返销*/
	String SRV_ESB_CS_SCORE_SCORE_BUYBACK_001 = "ESB_CS_SCORE_SCORE_BUYBACK_001";
	String MN_ESB_CS_SCORE_SCORE_BUYBACK_001 = ESB_URL + SRV_ESB_CS_SCORE_SCORE_BUYBACK_001;
	
	/**普通预销户@author bijun on 2014-10-9**/
	String SRV_ESB_SO_PERSONAL_GSM_DESTROY_001 = "ESB_SO_PERSONAL_GSM_DESTROY_001";
	String MN_ESB_SO_PERSONAL_GSM_DESTROY_001 = ESB_URL + SRV_ESB_SO_PERSONAL_GSM_DESTROY_001;
	
	/**终端发票打印查询@author mayc on 2014-10-14**/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_008 = "ESB_RES_NOTE_INVOICE_QRY_008";
	String MN_ESB_RES_NOTE_INVOICE_QRY_008 = ESB_URL + SRV_ESB_RES_NOTE_INVOICE_QRY_008;

	/**发票打印(终端)@author mayc on 2014-10-14**/
	String SRV_ESB_RES_NOTE_INVOICE_PRINT_008 = "ESB_RES_NOTE_INVOICE_PRINT_008";
	String MN_ESB_RES_NOTE_INVOICE_PRINT_008 = ESB_URL + SRV_ESB_RES_NOTE_INVOICE_PRINT_008;
	
	/**聊天获取token**/
	String SRV_ESB_BASE_IM_ACCESSTOKEN_QRY_001 = "ESB_BASE_IM_ACCESSTOKEN_QRY_001";
	String MN_ESB_BASE_IM_ACCESSTOKEN_QRY_001 = ESB_URL + "creatLoginToken";
	
	/**
	 * 二维码解析:将二维码信息提交到二维码平台，获得二维码对应的业务信息和业务参数
	 */
	String SRV_ESB_BASE_QRCODE_QRY_ANALYSE_001 = "ESB_BASE_QRCODE_QRY_ANALYSE_001";
	String MN_ESB_BASE_QRCODE_QRY_ANALYSE_001 = ESB_URL + "query";
	
	/**对账单近六个月消费明细查询接口@author bijun on 2014-10-28**/
	String SRV_ESB_CS_QRY_BILL_CUSTQRY_018 = "ESB_CS_QRY_BILL_CUSTQRY_018";
	String MN_ESB_CS_QRY_BILL_CUSTQRY_018 = ESB_URL + SRV_ESB_CS_QRY_BILL_CUSTQRY_018;
	
	/**个人历史对账单页面查询接口@author bijun on 2014-10-30**/
	String SRV_ESB_CS_QRY_BILL_CUSTQRY_016 = "ESB_CS_QRY_BILL_CUSTQRY_016";
	String MN_ESB_CS_QRY_BILL_CUSTQRY_016 = ESB_URL + SRV_ESB_CS_QRY_BILL_CUSTQRY_016;
	
	/**用户停开机受理接口  **/
	String SRV_ESB_CS_SC_SC_OPENSTOP_001 = "ESB_CS_SC_SC_OPENSTOP_001";
	String MN_ESB_CS_SC_SC_OPENSTOP_001 = ESB_URL + SRV_ESB_CS_SC_SC_OPENSTOP_001;
	
	/**业务变更提交受理接口  @author niwei on 2014-11-03**/
	String SRV_ESB_SO_PERSONAL_GSM_CHANGE_004 = "ESB_SO_PERSONAL_GSM_CHANGE_004";
	String MN_ESB_SO_PERSONAL_GSM_CHANGE_004 = ESB_URL + SRV_ESB_SO_PERSONAL_GSM_CHANGE_004;
	
	/**业务变更免填单预览接口  @author niwei on 2014-11-03**/
	String SRV_ESB_BASE_PRINT_BUSIPRINT_CONTENTQRY_002 = "ESB_BASE_PRINT_BUSIPRINT_CONTENTQRY_002";
	String MN_ESB_BASE_PRINT_BUSIPRINT_CONTENTQRY_002 = ESB_URL + SRV_ESB_BASE_PRINT_BUSIPRINT_CONTENTQRY_002;
	
	/**退订策划费用查询接口  @author niwei on 2014-11-03**/
	String SRV_ESB_CS_QRY_FEE_FEEQRY_001 = "ESB_CS_QRY_FEE_FEEQRY_001";
	String MN_ESB_CS_QRY_FEE_FEEQRY_001 = ESB_URL + SRV_ESB_CS_QRY_FEE_FEEQRY_001;
	
	/**操作员发票号查询@author xiesb on 2014-11-05**/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_009 = "ESB_RES_NOTE_INVOICE_QRY_009";
	String MN_ESB_RES_NOTE_INVOICE_QRY_009 = ESB_URL + SRV_ESB_RES_NOTE_INVOICE_QRY_009;
	
	/**获取渠道4G换卡验证码@author bijun on 2014-11-07**/
	String SRV_ESB_BASE_AUTH_IDECODE_GAIN_001 = "ESB_BASE_AUTH_IDECODE_GAIN_001";
	String MN_ESB_BASE_AUTH_IDECODE_GAIN_001 = ESB_URL + SRV_ESB_BASE_AUTH_IDECODE_GAIN_001;
	
	/**渠道4G换卡验证码校验	@author bijun on 2014-11-07**/
	String SRV_ESB_BASE_AUTH_4GCHGCARD_VERIFY_001 = "ESB_BASE_AUTH_4GCHGCARD_VERIFY_001";
	String MN_ESB_BASE_AUTH_4GCHGCARD_VERIFY_001 = ESB_URL + SRV_ESB_BASE_AUTH_4GCHGCARD_VERIFY_001;
	
	/**4G换卡办理	@author bijun on 2014-11-07**/
	String SRV_ESB_CS_SC_SC_CHANGECARD_001 = "ESB_CS_SC_SC_CHANGECARD_001";
	String MN_ESB_CS_SC_SC_CHANGECARD_001 = ESB_URL + SRV_ESB_CS_SC_SC_CHANGECARD_001;
	/**集团客户信息查询  @author yangrui on 2014-11-03**/
	String SRV_ESB_CS_QRY_MULTI_GRPQRY_001 = "ESB_CS_QRY_MULTI_GRPQRY_001_AISCRM";
	String MN_ESB_CS_QRY_MULTI_GRPQRY_001 = ESB_URL + "ESB_CS_QRY_MULTI_GRPQRY_001";

	/** 自带机查询终端IMEI信息 **/
	String SRV_ESB_SO_PERSONAL_SELFTMNL_CHECK_001 = "ESB_SO_PERSONAL_SELFTMNL_CHECK_001";
	String MN_ESB_SO_PERSONAL_SELFTMNL_CHECK_001 = ESB_URL + SRV_ESB_SO_PERSONAL_SELFTMNL_CHECK_001;
	
	/**退订策划费用查询接口  @author niwei on 2014-11-17**/
	String SRV_ESB_CS_QRY_OTHER_PREPAYQRY_001 = "ESB_CS_QRY_OTHER_PREPAYQRY_001";
	String MN_ESB_CS_QRY_OTHER_PREPAYQRY_001 = ESB_URL + SRV_ESB_CS_QRY_OTHER_PREPAYQRY_001;

	
	/**信息服务功能开关查询接口  @author weiwb on 2014-12-15**/
	String SRV_ESB_CS_QRY_DSMP_SWITCHQRY_001 = "ESB_CS_QRY_DSMP_SWITCHQRY_001";
	String MN_ESB_CS_QRY_DSMP_SWITCHQRY_001 = ESB_URL + SRV_ESB_CS_QRY_DSMP_SWITCHQRY_001;
	
	/**信息服务功能开关变更受理接口  @author weiwb on 2014-12-15**/
	String SRV_ESB_CS_DSMP_SWITCH_CHANGE_001 = "ESB_CS_DSMP_SWITCH_CHANGE_001";
	String MN_ESB_CS_DSMP_SWITCH_CHANGE_001 = ESB_URL + SRV_ESB_CS_DSMP_SWITCH_CHANGE_001;

	
	/** 宽带帐号校验 @author hc on 2014-11-20  **/
	String SRV_ESB_SO_PERSONAL_ORDER_CHECK_007="ESB_SO_PERSONAL_ORDER_CHECK_007";
	String MN_ESB_SO_PERSONAL_ORDER_CHECK_007=ESB_URL+SRV_ESB_SO_PERSONAL_ORDER_CHECK_007;
	
	/** 群组业务组网 @author hc on 2014-11-20  **/
	String SRV_ESB_SO_PERSONAL_GROUP_ORDER_002="ESB_SO_PERSONAL_GROUP_ORDER_002";
	String MN_ESB_SO_PERSONAL_GROUP_ORDER_002=ESB_URL+SRV_ESB_SO_PERSONAL_GROUP_ORDER_002;
	
	/**个人库存---start */
	/** 实物申请单查询*/
	String SRV_ESB_RES_ENTITY_STOCK_APPLYQRY_001 = "ESB_RES_ENTITY_STOCK_APPLYQRY_001";
	String MN_ESB_RES_ENTITY_STOCK_APPLYQRY_001 = ESB_URL+SRV_ESB_RES_ENTITY_STOCK_APPLYQRY_001;
	/** 审批单全部接收*/
	String SRV_ESB_RES_ENTITY_STOCK_RECEIVE_001 = "ESB_RES_ENTITY_STOCK_RECEIVE_001";
	String MN_ESB_RES_ENTITY_STOCK_RECEIVE_001 = ESB_URL+SRV_ESB_RES_ENTITY_STOCK_RECEIVE_001;
	/** 明细查询*/
	String SRV_ESB_RES_ENTITY_STOCK_DTLQRY_001 = "ESB_RES_ENTITY_STOCK_DTLQRY_001";
	String MN_ESB_RES_ENTITY_STOCK_DTLQRY_001 = ESB_URL+SRV_ESB_RES_ENTITY_STOCK_DTLQRY_001;
	/** 库存查询*/
	String SRV_ESB_RES_ENTITY_STOCK_QRY_002 = "ESB_RES_ENTITY_STOCK_QRY_002";
	String MN_ESB_RES_ENTITY_STOCK_QRY_002 = ESB_URL+SRV_ESB_RES_ENTITY_STOCK_QRY_002;
	/** 库存回退*/
	String SRV_ESB_RES_ENTITY_STOCK_STOCKROLLBACK_001 = "ESB_RES_ENTITY_STOCK_STOCKROLLBACK_001";
	String MN_ESB_RES_ENTITY_STOCK_STOCKROLLBACK_001 = ESB_URL+SRV_ESB_RES_ENTITY_STOCK_STOCKROLLBACK_001;
	/** 实物申请*/
	String SRV_ESB_RES_ENTITY_STOCK_STOCKAPPLY_001 = "ESB_RES_ENTITY_STOCK_STOCKAPPLY_001";
	String MN_ESB_RES_ENTITY_STOCK_STOCKAPPLY_001 = ESB_URL+SRV_ESB_RES_ENTITY_STOCK_STOCKAPPLY_001;
	/** 实物库存量查询*/
	String SRV_ESB_RES_ENTITY_STOCK_QRY_001 = "ESB_RES_ENTITY_STOCK_QRY_001";
	String MN_ESB_RES_ENTITY_STOCK_QRY_001 = ESB_URL+SRV_ESB_RES_ENTITY_STOCK_QRY_001;
	/**个人库存------end*/
	
	/**客户经理信息查询 @author yangrui on 2014-11-03**/
	String SRV_ESB_CS_QRY_OTHER_MANAGERQRY_001 = "ESB_CS_QRY_OTHER_MANAGERQRY_001_AISCRM";
	String MN_ESB_CS_QRY_OTHER_MANAGERQRY_001 = ESB_URL + "ESB_CS_QRY_OTHER_MANAGERQRY_001";
	
	/** 群组套餐变更 @author hc on 2014-11-20  **/
	String SRV_ESB_SO_PERSONAL_GROUP_OFFERCHANGE_001="ESB_SO_PERSONAL_GROUP_OFFERCHANGE_001";
	String MN_ESB_SO_PERSONAL_GROUP_OFFERCHANGE_001=ESB_URL+SRV_ESB_SO_PERSONAL_GROUP_OFFERCHANGE_001;
	
	/** 有线宽带开户 @author xiesb on 2014-11-28  **/
	String SRV_ESB_SO_PERSONAL_WB_ORDER_002 = "ESB_SO_PERSONAL_WB_ORDER_002";
	String MN_ESB_SO_PERSONAL_WB_ORDER_002 = ESB_URL+SRV_ESB_SO_PERSONAL_WB_ORDER_002;
	
	
	/** 宽带策划可订购生失效时间查询 @author hc on 2014-12-09  **/
	String SRV_ESB_SO_PERSONAL_WB_OFFDATEQRY_001="ESB_SO_PERSONAL_WB_OFFDATEQRY_001";
	String MN_ESB_SO_PERSONAL_WB_OFFDATEQRY_001=ESB_URL+SRV_ESB_SO_PERSONAL_WB_OFFDATEQRY_001;
	
	/** 用户星级信息查询@author bijun on 2014-12-16  **/
	String SRV_ESB_CS_SC_CREDIT_STARQRY_001="ESB_CS_SC_CREDIT_STARQRY_001";
	String MN_ESB_CS_SC_CREDIT_STARQRY_001=ESB_URL+SRV_ESB_CS_SC_CREDIT_STARQRY_001;
	
	/** 用户星级透支服务开通/取消@author bijun on 2014-12-17  **/
	String SRV_ESB_CS_SC_CREDIT_OVERCHG_001="ESB_CS_SC_CREDIT_OVERCHG_001";
	String MN_ESB_CS_SC_CREDIT_OVERCHG_001=ESB_URL+SRV_ESB_CS_SC_CREDIT_OVERCHG_001;
	
	/** 家庭套餐成员查询@author bijun on 2014-12-17  **/
	String SRV_ESB_SO_FAMILY_FAMILY_QRY_001="ESB_SO_FAMILY_FAMILY_QRY_001";
	String MN_ESB_SO_FAMILY_FAMILY_QRY_001=ESB_URL+SRV_ESB_SO_FAMILY_FAMILY_QRY_001;
	
	/** 亲情通成员信息查询@author bijun on 2014-12-18  **/
	String SRV_ESB_SO_PERSONAL_FAMILY_QRY_001="ESB_SO_PERSONAL_FAMILY_QRY_001";
	String MN_ESB_SO_PERSONAL_FAMILY_QRY_001=ESB_URL+SRV_ESB_SO_PERSONAL_FAMILY_QRY_001;
	
	/** 群组终端流量共享成员查询@author bijun on 2014-12-18  **/
	String SRV_ESB_SO_GROUP_TMNL_QRY_001="ESB_SO_GROUP_TMNL_QRY_001";
	String MN_ESB_SO_GROUP_TMNL_QRY_001=ESB_URL+SRV_ESB_SO_GROUP_TMNL_QRY_001;
	
	/** 一机双号查询@author bijun on 2014-12-18  **/
	String SRV_ESB_SO_GROUP_DUALNUM_QRY_001="ESB_SO_GROUP_DUALNUM_QRY_001";
	String MN_ESB_SO_GROUP_DUALNUM_QRY_001=ESB_URL+SRV_ESB_SO_GROUP_DUALNUM_QRY_001;

	/**  GPRS重置 @author wangshuai7     **/
	String SRV_ESB_SO_PERSONAL_GPRS_RESET_001 = "ESB_SO_PERSONAL_GPRS_RESET_001";
	String MN_ESB_SO_PERSONAL_GPRS_RESET_001 = ESB_URL+SRV_ESB_SO_PERSONAL_GPRS_RESET_001;
	

	/** 宽带密码修改 @author jiaotd**/
	String SRV_ESB_BASE_AUTH_PWD_CHANGE_001 = "ESB_BASE_AUTH_PWD_CHANGE_001";
	String MN_ESB_BASE_AUTH_PWD_CHANGE_001 = ESB_URL+SRV_ESB_BASE_AUTH_PWD_CHANGE_001;
	
	/** 宽带密码重置 @author jiaotd**/
	String SRV_ESB_BASE_AUTH_PWD_RESET_001 = "ESB_BASE_AUTH_PWD_RESET_001";
	String MN_ESB_BASE_AUTH_PWD_RESET_001 = ESB_URL+SRV_ESB_BASE_AUTH_PWD_RESET_001;

	/** 宽带拆机*/
	String SRV_ESB_SO_PERSONAL_WB_QRY_006 = "ESB_SO_PERSONAL_WB_QRY_006";
	String MN_ESB_SO_PERSONAL_WB_QRY_006 = ESB_URL+SRV_ESB_SO_PERSONAL_WB_QRY_006;

	
	/** 根据SIM卡查询用户信息 @author weiwb **/
	String SRV_ESB_RES_SIM_SIM_QRY_004 = "ESB_RES_SIM_SIM_QRY_004";
	String MN_ESB_RES_SIM_SIM_QRY_004 = ESB_URL+SRV_ESB_RES_SIM_SIM_QRY_004;

	
	String SRV_ESB_SO_PERSONAL_WB_CANCEL_001 = "ESB_SO_PERSONAL_WB_CANCEL_001";
	String MN_ESB_SO_PERSONAL_WB_CANCEL_001 = ESB_URL+SRV_ESB_SO_PERSONAL_WB_CANCEL_001;
	
	/** 宽带费用信息查询 @author xiesb on 2014-12-22  **/
	String SRV_ESB_SO_PERSONAL_WB_FEEINFOQRY_001 = "ESB_SO_PERSONAL_WB_FEEINFOQRY_001";
	String MN_ESB_SO_PERSONAL_WB_FEEINFOQRY_001 = ESB_URL+SRV_ESB_SO_PERSONAL_WB_FEEINFOQRY_001;
	
	/** 宽带拆机获取提示信息  **/
	String SRV_ESB_SO_PERSONAL_WB_QRY_005 = "ESB_SO_PERSONAL_WB_QRY_005";
	String MN_ESB_SO_PERSONAL_WB_QRY_005 = ESB_URL+SRV_ESB_SO_PERSONAL_WB_QRY_005;
	
	/** 黑名单号码查询 **/
	String SRV_ESB_CS_QRY_CM_BLACKQRY_001 = "ESB_CS_QRY_CM_BLACKQRY_001";
	String MN_ESB_CS_QRY_CM_BLACKQRY_001 = ESB_URL+SRV_ESB_CS_QRY_CM_BLACKQRY_001;
	
	/** 黑名单用户受理记录查询 **/
	String SRV_ESB_CS_QRY_CM_BLACKQRY_002 = "ESB_CS_QRY_CM_BLACKQRY_002";
	String MN_ESB_CS_QRY_CM_BLACKQRY_002 = ESB_URL+SRV_ESB_CS_QRY_CM_BLACKQRY_002;
	
	/** 黑名单用户解除 **/
	String SRV_ESB_CS_SC_SC_BLACKREMOVE_001 = "ESB_CS_SC_SC_BLACKREMOVE_001";
	String MN_ESB_CS_SC_SC_BLACKREMOVE_001 = ESB_URL+SRV_ESB_CS_SC_SC_BLACKREMOVE_001;
	
	/**  查询用户某月联系人数量  @author wangshuai7     **/
	String SRV_ESB_SO_PERSONAL_QRY_CONTACT_001 = "ESB_SO_PERSONAL_QRY_CONTACT_001";
	String MN_ESB_SO_PERSONAL_QRY_CONTACT_001 = ESB_URL + SRV_ESB_SO_PERSONAL_QRY_CONTACT_001;


	/**  宽带增值策划受理   @author mayc     **/
	String SRV_ESB_SO_PERSONAL_WB_VASORDER_001 = "ESB_SO_PERSONAL_WB_VASORDER_001";
	String MN_ESB_SO_PERSONAL_WB_VASORDER_001 = ESB_URL + SRV_ESB_SO_PERSONAL_WB_VASORDER_001;
	
	/** 宽带移机*/
	String SRV_ESB_SO_PERSONAL_WB_MOVE_001 = "ESB_SO_PERSONAL_WB_MOVE_001";
	String MN_ESB_SO_PERSONAL_WB_MOVE_001 = ESB_URL+SRV_ESB_SO_PERSONAL_WB_MOVE_001;

	/** ESB_SO_GROUP_TMNL_QRY_002  群组终端流量共享流量查询   add by hc */
	String SRV_ESB_SO_GROUP_TMNL_QRY_002 = "ESB_SO_GROUP_TMNL_QRY_002";
	String MN_ESB_SO_GROUP_TMNL_QRY_002 = ESB_URL+SRV_ESB_SO_GROUP_TMNL_QRY_002;

	/** ESB_SO_PERSONAL_FN_QRY_003  亲情网共享流量包流量查询  add by hc */

 	String SRV_ESB_SO_PERSONAL_FN_QRY_003 = "ESB_SO_PERSONAL_FN_QRY_003";
	String MN_ESB_SO_PERSONAL_FN_QRY_003 = ESB_URL+SRV_ESB_SO_PERSONAL_FN_QRY_003;
	
	/** 押金查询*/
	String SRV_ESB_CS_QRY_FEE_DEPOSITQRY_001 = "ESB_CS_QRY_FEE_DEPOSITQRY_001";
	String MN_ESB_CS_QRY_FEE_DEPOSITQRY_001 = ESB_URL+SRV_ESB_CS_QRY_FEE_DEPOSITQRY_001;
	
	/** 宽带体验体验升级处理记录查询*/
	String SRV_ESB_SO_PERSONAL_WB_SPDDEALQRY_001 = "ESB_SO_PERSONAL_WB_SPDDEALQRY_001";
	String MN_ESB_SO_PERSONAL_WB_SPDDEALQRY_001 = ESB_URL+SRV_ESB_SO_PERSONAL_WB_SPDDEALQRY_001;
	
	
	/** 用户扩展属性查询 */
	
	String SRV_ESB_CS_QRY_MULTI_MULTIQRY_022 = "ESB_CS_QRY_MULTI_MULTIQRY_022";
	String MN_ESB_CS_QRY_MULTI_MULTIQRY_022 = ESB_URL+SRV_ESB_CS_QRY_MULTI_MULTIQRY_022;
	
	/**宽带发票打印项目查询 @author xiesb on 2014-1-06**/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_010 = "ESB_RES_NOTE_INVOICE_QRY_010";
	String MN_ESB_RES_NOTE_INVOICE_QRY_010 = ESB_URL + SRV_ESB_RES_NOTE_INVOICE_QRY_010;
	
	
	/** 店员信息查询   ESB_CHNL_CLERK_INFO_QRY_001*/
	String SRV_ESB_CHNL_CLERK_INFO_QRY_001 = "ESB_CHNL_CLERK_INFO_QRY_001";
	String MN_ESB_CHNL_CLERK_INFO_QRY_001 = ESB_URL + SRV_ESB_CHNL_CLERK_INFO_QRY_001;
	
	/** 用户满意度短信下发 ESB_CS_SC_LOGOUT_SATISFY_001*/
	String SRV_ESB_CS_SC_LOGOUT_SATISFY_001 = "ESB_CS_SC_LOGOUT_SATISFY_001";
	String MN_ESB_CS_SC_LOGOUT_SATISFY_001 = ESB_URL + SRV_ESB_CS_SC_LOGOUT_SATISFY_001;
	
	/** 流量账户收支明细查询*/
	String SRV_ESB_CS_AMS_FM_ACCTDTLQRY_001 = "ESB_CS_AMS_FM_ACCTDTLQRY_001";
	String MN_ESB_CS_AMS_FM_ACCTDTLQRY_001 = ESB_URL + SRV_ESB_CS_AMS_FM_ACCTDTLQRY_001;
	
	/** 补换卡可选资源规格查询 @author bijun*/
	String SRV_ESB_RES_RES_QRY_SPECQRY_004 = "ESB_RES_RES_QRY_SPECQRY_004";
	String MN_ESB_RES_RES_QRY_SPECQRY_004 = ESB_URL + SRV_ESB_RES_RES_QRY_SPECQRY_004;
	
	/** 资源关联资源规格查询 @author bijun*/
	String SRV_ESB_RES_RES_QRY_SPECQRY_003 = "ESB_RES_RES_QRY_SPECQRY_003";
	String MN_ESB_RES_RES_QRY_SPECQRY_003 = ESB_URL + SRV_ESB_RES_RES_QRY_SPECQRY_003;
	
	/**用户特性推荐标签（用户画像）查询   wangshuai7*/
	String SRV_ESB_SSM_CAMP_CAMP_RCM_002 = "ESB_SSM_CAMP_CAMP_RCM_002";
	String MN_ESB_SSM_CAMP_CAMP_RCM_002 = ESB_URL + SRV_ESB_SSM_CAMP_CAMP_RCM_002;


	/**  宽带业务变更   @author mayc  on 2015-02-02  **/
	String SRV_ESB_SO_PERSONAL_WB_CHANGE_001 = "ESB_SO_PERSONAL_WB_CHANGE_001";
	String MN_ESB_SO_PERSONAL_WB_CHANGE_001 = ESB_URL + SRV_ESB_SO_PERSONAL_WB_CHANGE_001;

	
	/** 流量专区流量包推荐查询     @author wangshuai7  on 2015-03-27*/
	String SRV_ESB_CS_QRY_FLOWZONE_FLOWQRY_002 = "ESB_CS_QRY_FLOWZONE_FLOWQRY_002";
	String MN_ESB_CS_QRY_FLOWZONE_FLOWQRY_002 = ESB_URL + SRV_ESB_CS_QRY_FLOWZONE_FLOWQRY_002;
	
	
	/** 流量专区信息查询   */
	String SRV_ESB_CS_QRY_FLOWZONE_FLOWQRY_001 = "ESB_CS_QRY_FLOWZONE_FLOWQRY_001";
	String MN_ESB_CS_QRY_FLOWZONE_FLOWQRY_001 = ESB_URL + SRV_ESB_CS_QRY_FLOWZONE_FLOWQRY_001;
	
	/**  常态机销售反撤   @author wangshuai7  on 2015-03-03  **/
	String SRV_ESB_RES_TMNL_TMNL_REFUND_001 = "ESB_RES_TMNL_TMNL_REFUND_001";
	String MN_ESB_RES_TMNL_TMNL_REFUND_001 = ESB_URL + SRV_ESB_RES_TMNL_TMNL_REFUND_001;
	
	
	/**  常态机终端退机   @author wangshuai7  on 2015-03-03  **/
	String SRV_ESB_RES_TMNL_TMNL_BACK_001 = "ESB_RES_TMNL_TMNL_BACK_001";
	String MN_ESB_RES_TMNL_TMNL_BACK_001 = ESB_URL + SRV_ESB_RES_TMNL_TMNL_BACK_001;
	
	
	/**  用户终端销售记录查询   @author wangshuai7  on 2015-03-03  **/
	String SRV_ESB_CS_QRY_OTHER_TMNLQRY_002 = "ESB_CS_QRY_OTHER_TMNLQRY_002";
	String MN_ESB_CS_QRY_OTHER_TMNLQRY_002 = ESB_URL + SRV_ESB_CS_QRY_OTHER_TMNLQRY_002;
	
	
	/**  充值卡状态校验   @author wangshuai7  on 2015-03-04  **/
	String SRV_ESB_CS_AMS_CHARGE_CHECK_001 = "ESB_CS_AMS_CHARGE_CHECK_001";
	String MN_ESB_CS_AMS_CHARGE_CHECK_001 = ESB_URL + SRV_ESB_CS_AMS_CHARGE_CHECK_001;
	
	/**  终端换机   @author jiaotd  on 2015-03-03  **/
	String SRV_ESB_RES_TMNL_TMNL_CHGMBL_001 = "ESB_RES_TMNL_TMNL_CHGMBL_001";
	String MN_ESB_RES_TMNL_TMNL_CHGMBL_001 =ESB_URL + SRV_ESB_RES_TMNL_TMNL_CHGMBL_001;
	

	/**  预缴反充记录查询   @author hc on 2015-03-05  **/
	String SRV_ESB_CS_QRY_RECORD_PREPAY_001 = "ESB_CS_QRY_RECORD_PREPAY_001";
	String MN_ESB_CS_QRY_RECORD_PREPAY_001 =ESB_URL + SRV_ESB_CS_QRY_RECORD_PREPAY_001;
	
	/** 在线支付流水号生成*/
	String SRV_ESB_SO_PERSONAL_ONLINEPAY_DEAL_001 = "ESB_SO_PERSONAL_ONLINEPAY_DEAL_001";
	String MN_ESB_SO_PERSONAL_ONLINEPAY_DEAL_001 = ESB_URL + SRV_ESB_SO_PERSONAL_ONLINEPAY_DEAL_001;
	
	/** 在线支付退款详情查询*/
	String SRV_ESB_SO_PERSONAL_ONLINEPAY_QRY_001 = "ESB_SO_PERSONAL_ONLINEPAY_QRY_001";
	String MN_ESB_SO_PERSONAL_ONLINEPAY_QRY_001 = ESB_URL + SRV_ESB_SO_PERSONAL_ONLINEPAY_QRY_001;
	
	/**  业务关联发票查询   @author mayc  on 2015-03-05   **/
	String SRV_ESB_RES_NOTE_INVOICE_RLTBUSIQRY_001 = "ESB_RES_NOTE_INVOICE_RLTBUSIQRY_001";
	String MN_ESB_RES_NOTE_INVOICE_RLTBUSIQRY_001 = ESB_URL + SRV_ESB_RES_NOTE_INVOICE_RLTBUSIQRY_001;

	/**  发票作废查询   @author mayc  on 2015-03-05   **/
	String SRV_ESB_RES_NOTE_INVOICE_SCRAPAPPLYQRY_001 = "ESB_RES_NOTE_INVOICE_SCRAPAPPLYQRY_001";
	String MN_ESB_RES_NOTE_INVOICE_SCRAPAPPLYQRY_001 = ESB_URL + SRV_ESB_RES_NOTE_INVOICE_SCRAPAPPLYQRY_001;

	/** 发票作废申请   @author mayc  on 2015-03-05  **/
	String SRV_ESB_RES_NOTE_INVOICE_SCRAP_001 = "ESB_RES_NOTE_INVOICE_SCRAP_001";
	String MN_ESB_RES_NOTE_INVOICE_SCRAP_001 = ESB_URL + SRV_ESB_RES_NOTE_INVOICE_SCRAP_001;

	/** 实时费用查询   @author mayc  on 2015-03-18  **/
	String SRV_ESB_CS_QRY_RECORD_BILLFEE_003 = "ESB_CS_QRY_RECORD_BILLFEE_003";
	String MN_ESB_CS_QRY_RECORD_BILLFEE_003 = ESB_URL +SRV_ESB_CS_QRY_RECORD_BILLFEE_003;

	/** 一次性费用实时打印信息查询   @author mayc  on 2015-03-23  **/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_011 = "ESB_RES_NOTE_INVOICE_QRY_011";
	String MN_ESB_RES_NOTE_INVOICE_QRY_011 = ESB_URL + SRV_ESB_RES_NOTE_INVOICE_QRY_011;

	/** 一次性费用实时打印   @author mayc  on 2015-03-27  **/
	String SRV_ESB_RES_NOTE_INVOICE_PRINT_009 = "ESB_RES_NOTE_INVOICE_PRINT_009";
	String MN_ESB_RES_NOTE_INVOICE_PRINT_009 = ESB_URL + SRV_ESB_RES_NOTE_INVOICE_PRINT_009;
	
	/** 使用人信息查询    @author bijun  on 2015-05-15 **/
	String SRV_ESB_CS_QRY_OTHER_OWNERQRY_001 = "ESB_CS_QRY_OTHER_OWNERQRY_001";
	String MN_ESB_CS_QRY_OTHER_OWNERQRY_001 = ESB_URL + SRV_ESB_CS_QRY_OTHER_OWNERQRY_001;
	
	/** 用户终端信息查询    @author bijun  on 2015-05-15 **/
	String SRV_ESB_CS_QRY_OTHER_TMNLQRY_001 = "ESB_CS_QRY_OTHER_TMNLQRY_001";
	String MN_ESB_CS_QRY_OTHER_TMNLQRY_001 = ESB_URL + SRV_ESB_CS_QRY_OTHER_TMNLQRY_001;
	
	/**用户策划订单信息查询*/
	String SRV_ESB_SO_PERSONAL_OFFER_ORDQRY_001 = "ESB_SO_PERSONAL_OFFER_ORDQRY_001";
	String MN_ESB_SO_PERSONAL_OFFER_ORDQRY_001 = ESB_URL + SRV_ESB_SO_PERSONAL_OFFER_ORDQRY_001;
	
	/**用户终端业务记录查询*/
	String SRV_ESB_RES_TMNL_BUSIREC_QRY_001 = "ESB_RES_TMNL_BUSIREC_QRY_001";
	String MN_ESB_RES_TMNL_BUSIREC_QRY_001 = ESB_URL + SRV_ESB_RES_TMNL_BUSIREC_QRY_001;
	
	/**退费订单查询*/
	String SRV_ESB_SO_PERSONAL_ORDER_DTLQRY_001 = "ESB_SO_PERSONAL_ORDER_DTLQRY_001";
	String MN_ESB_SO_PERSONAL_ORDER_DTLQRY_001 = ESB_URL + SRV_ESB_SO_PERSONAL_ORDER_DTLQRY_001;
	
	/**宽带属性变更*/
	String SRV_ESB_SO_PERSONAL_WB_ATTRCHANGE_001 = "ESB_SO_PERSONAL_WB_ATTRCHANGE_001";
	String MN_ESB_SO_PERSONAL_WB_ATTRCHANGE_001 = ESB_URL + SRV_ESB_SO_PERSONAL_WB_ATTRCHANGE_001;
	
	/**渠道账务资金变化明细@author fengjx on 2015-05-29**/
	String SRV_ESB_CHNL_FUND_FUNDPOOL_QRY_001 = "ESB_CHNL_FUND_FUNDPOOL_QRY_001";
	String MN_ESB_CHNL_FUND_FUNDPOOL_QRY_001 = ESB_URL+SRV_ESB_CHNL_FUND_FUNDPOOL_QRY_001;
	
	/**集团成员列表查询（原集团成员信息查询）@author bijun on 2015-06-1**/
	String SRV_ESB_CS_QRY_MULTI_MEMBERQRY_001 = "ESB_CS_QRY_MULTI_MEMBERQRY_001";
	String MN_ESB_CS_QRY_MULTI_MEMBERQRY_001 = ESB_URL+SRV_ESB_CS_QRY_MULTI_MEMBERQRY_001;
	
	/**集团客户关联的客户经理查询@author bijun on 2015-06-1**/
	String SRV_ESB_CM_GROUP_MANAGER_QRY_002 = "ESB_CM_GROUP_MANAGER_QRY_002";
	String MN_ESB_CM_GROUP_MANAGER_QRY_002 = ESB_URL+SRV_ESB_CM_GROUP_MANAGER_QRY_002;
		
	/**历史账户查询*/
	String SRV_ESB_CS_QRY_ACC_HISQRY_001 = "ESB_CS_QRY_ACC_HISQRY_001";
	String MN_ESB_CS_QRY_ACC_HISQRY_001 = ESB_URL + SRV_ESB_CS_QRY_ACC_HISQRY_001;
	
	/**历史策划信息查询@author niwei on 2015-06-04 **/
	String SRV_ESB_SO_PERSONAL_OFFER_HISQRY_001 = "ESB_SO_PERSONAL_OFFER_HISQRY_001";
	String MN_ESB_SO_PERSONAL_OFFER_HISQRY_001 = ESB_URL + SRV_ESB_SO_PERSONAL_OFFER_HISQRY_001;

	/**预缴反冲规则查询@authordongjf on 2015-06-09 **/
	String SRV_ESB_SO_PERSONAL_PREPAY_QRY_002 = "ESB_SO_PERSONAL_PREPAY_QRY_002";
	String MN_ESB_SO_PERSONAL_PREPAY_QRY_002 = ESB_URL + SRV_ESB_SO_PERSONAL_PREPAY_QRY_002;
	
	/**担保人信息查询@authordongjf on 2015-06-11 **/
	String SRV_ESB_SO_TMNL_BIND_QRY_001 = "ESB_SO_TMNL_BIND_QRY_001";
	String MN_ESB_SO_TMNL_BIND_QRY_001 = ESB_URL + SRV_ESB_SO_TMNL_BIND_QRY_001;

	
	/**手机和固网押金查询@author wangshan on 2015-06-12 **/
	String SRV_ESB_CS_QRY_AMS_DEPOSITINFOQRY_001 = "ESB_CS_QRY_AMS_DEPOSITINFOQRY_001";
	String MN_ESB_CS_QRY_AMS_DEPOSITINFOQRY_001 = ESB_URL + SRV_ESB_CS_QRY_AMS_DEPOSITINFOQRY_001;
	
	/**押金用户查询@author wangshan on 2015-06-13 **/
	String SRV_ESB_CS_QRY_AMS_DEPOSITUSERQRY_001 = "ESB_CS_QRY_AMS_DEPOSITUSERQRY_001";
	String MN_ESB_CS_QRY_AMS_DEPOSITUSERQRY_001 = ESB_URL + SRV_ESB_CS_QRY_AMS_DEPOSITUSERQRY_001;
	
	/**押金变更记录查询@author wangshan on 2015-06-15 **/
	String SRV_ESB_CS_QRY_AMS_DEPOSITCHGRECQRY_001 = "ESB_CS_QRY_AMS_DEPOSITCHGRECQRY_001";
	String MN_ESB_CS_QRY_AMS_DEPOSITCHGRECQRY_001 = ESB_URL + SRV_ESB_CS_QRY_AMS_DEPOSITCHGRECQRY_001;
	
	/**固网押金管理补收及收费@author wangshan on 2015-06-15 **/
	String SRV_ESB_CS_AMS_FUND_DEPOSITCHARGE_001 = "ESB_CS_AMS_FUND_DEPOSITCHARGE_001";
	String MN_ESB_CS_AMS_FUND_DEPOSITCHARGE_001 = ESB_URL + SRV_ESB_CS_AMS_FUND_DEPOSITCHARGE_001;
	
	/**手机和固网手机押金退费@author wangshan on 2015-06-15 **/
	String SRV_ESB_CS_AMS_FUND_DEPOSITREFUND_001 = "ESB_CS_AMS_FUND_DEPOSITREFUND_001";
	String MN_ESB_CS_AMS_FUND_DEPOSITREFUND_001 = ESB_URL + SRV_ESB_CS_AMS_FUND_DEPOSITREFUND_001;
	
	/**用户账单发票打印明细查询 @author mayc on 2015-06-16 **/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_012 = "ESB_RES_NOTE_INVOICE_QRY_012";
	String MN_ESB_RES_NOTE_INVOICE_QRY_012 = ESB_URL + SRV_ESB_RES_NOTE_INVOICE_QRY_012;

	String SRV_ESB_RES_PRE_NUM_QRY_001 = "ESB_RES_PRE_NUM_QRY_001";
	String MN_ESB_RES_PRE_NUM_QRY_001 = ESB_URL + SRV_ESB_RES_PRE_NUM_QRY_001;
	
	String SRV_ESB_SSM_CAMP_CAMP_RCM_003 = "ESB_SSM_CAMP_CAMP_RCM_003";
	String MN_ESB_SSM_CAMP_CAMP_RCM_003 = ESB_URL + SRV_ESB_SSM_CAMP_CAMP_RCM_003;
	
	/**收货地址查询 @author zhangmm3 on 2015-06-23 **/
    String SRV_ESB_CHNL_RES_INFO_QRY_001 = "ESB_CHNL_RES_INFO_QRY_001";
    String MN_ESB_CHNL_RES_INFO_QRY_001 = ESB_URL + SRV_ESB_CHNL_RES_INFO_QRY_001;

    /**乡镇信息查询 @author zhangmm3 on 2015-06-24 **/
    String SRV_ESB_CHNL_QRY_INFO_PARAMQRY_001 = "ESB_CHNL_QRY_INFO_PARAMQRY_001";
    String MN_ESB_CHNL_QRY_INFO_PARAMQRY_001 = ESB_URL + SRV_ESB_CHNL_QRY_INFO_PARAMQRY_001;

    /**更新收货地址 @author zhangmm3 on 2015-06-24 **/
    String SRV_ESB_CHNL_RES_INFO_MODIFY_001 = "ESB_CHNL_RES_INFO_MODIFY_001";
    String MN_ESB_CHNL_RES_INFO_MODIFY_001 = ESB_URL + SRV_ESB_CHNL_RES_INFO_MODIFY_001;

    /**查询产品信息及规则 @author zhangmm3 on 2015-06-24 **/
    String SRV_ESB_CHNL_RES_PRODUCT_QRY_001 = "ESB_CHNL_RES_PRODUCT_QRY_001";
    String MN_ESB_CHNL_RES_PRODUCT_QRY_001 = ESB_URL + SRV_ESB_CHNL_RES_PRODUCT_QRY_001;

    /**卡包订购提交 @author zhangmm3 on 2015-06-25 **/
    String SRV_ESB_SO_PERSONAL_GSM_CARDBAGDEAL_001 = "ESB_SO_PERSONAL_GSM_CARDBAGDEAL_001";
    String MN_ESB_SO_PERSONAL_GSM_CARDBAGDEAL_001 = ESB_URL + SRV_ESB_SO_PERSONAL_GSM_CARDBAGDEAL_001;

    /**资金池查询 @author zhangmm3 on 2015-06-26 **/
    String SRV_ESB_CHNL_FUND_BAL_QRY_001 = "ESB_CHNL_FUND_BAL_QRY_001";
    String MN_ESB_CHNL_FUND_BAL_QRY_001 = ESB_URL + SRV_ESB_CHNL_FUND_BAL_QRY_001;

    /**查询订单列表信息 @author zhangmm3 on 2015-06-26 **/
    String SRV_ESB_CHNL_RES_ORDER_QRY_001 = "ESB_CHNL_RES_ORDER_QRY_001";
    String MN_ESB_CHNL_RES_ORDER_QRY_001 = ESB_URL + SRV_ESB_CHNL_RES_ORDER_QRY_001;

    
    /**群组业务变更 @author wangshan on 2015-07-02**/
    String SRV_ESB_SO_PERSONAL_GROUP_ORDER_003 = "ESB_SO_PERSONAL_GROUP_ORDER_003";
    String MN_ESB_SO_PERSONAL_GROUP_ORDER_003 = ESB_URL + SRV_ESB_SO_PERSONAL_GROUP_ORDER_003;
    
    /** 群组套餐变更 @author wangshan on 2015-07-02**/
	String SRV_ESB_SO_PERSONAL_GROUP_OFFERCHANGE_002="ESB_SO_PERSONAL_GROUP_OFFERCHANGE_002";
	String MN_ESB_SO_PERSONAL_GROUP_OFFERCHANGE_002=ESB_URL+SRV_ESB_SO_PERSONAL_GROUP_OFFERCHANGE_002;
	
	 /** 亲情网申请加入 @author zhouqishan on 2016-08-26**/
	String SRV_ESB_SO_PERSONAL_FN_MEMBERDEVELOP_001="ESB_SO_PERSONAL_FN_MEMBERDEVELOP_001";
	String MN_ESB_SO_PERSONAL_FN_MEMBERDEVELOP_001=ESB_URL+SRV_ESB_SO_PERSONAL_FN_MEMBERDEVELOP_001;
  
    /**一卡多号查询 **/
    String SRV_ESB_SO_PERSONAL_MULNUM_QRY_001 = "ESB_SO_PERSONAL_MULNUM_QRY_001";
    String MN_ESB_SO_PERSONAL_MULNUM_QRY_001 = ESB_URL + SRV_ESB_SO_PERSONAL_MULNUM_QRY_001;
	
    /**订单查询 **/
    String SRV_ESB_CHNL_RES_ORDER_QRY_002 = "ESB_CHNL_RES_ORDER_QRY_002";
    String MN_ESB_CHNL_RES_ORDER_QRY_002 = ESB_URL + SRV_ESB_CHNL_RES_ORDER_QRY_002;
    
    /**流量套餐预约记录查询 **/
    String SRV_ESB_SO_PERSONAL_PREREGISTER_QRY_001 = "ESB_SO_PERSONAL_PREREGISTER_QRY_001";
    String MN_ESB_SO_PERSONAL_PREREGISTER_QRY_001 = ESB_URL + SRV_ESB_SO_PERSONAL_PREREGISTER_QRY_001;

    /**外省充值发票打印 @author mayc on 2015-07-20**/
	String SRV_ESB_RES_NOTE_INVOICE_PRINT_010 = "ESB_RES_NOTE_INVOICE_PRINT_010";
	String MN_ESB_RES_NOTE_INVOICE_PRINT_010 = ESB_URL + SRV_ESB_RES_NOTE_INVOICE_PRINT_010;
	
	/**流量专区充值 */
	String SRV_ESB_CS_AMS_FM_FLOWUNREALCHARGE_001 = "ESB_CS_AMS_FM_FLOWUNREALCHARGE_001";
	String MN_ESB_CS_AMS_FM_FLOWUNREALCHARGE_001 = ESB_URL + SRV_ESB_CS_AMS_FM_FLOWUNREALCHARGE_001;  

	/**多终端流量群组共享创建 */
	String SRV_ESB_SO_GROUP_TMNL_CREATE_001 = "ESB_SO_GROUP_TMNL_CREATE_001";
	String MN_ESB_SO_GROUP_TMNL_CREATE_001 = ESB_URL + SRV_ESB_SO_GROUP_TMNL_CREATE_001;
	
	/**多终端流量共享群组成员变更 **/
	String SRV_ESB_SO_GROUP_TMNL_CHANGE_001 = "ESB_SO_GROUP_TMNL_CHANGE_001";
	String MN_ESB_SO_GROUP_TMNL_CHANGE_001 = ESB_URL + SRV_ESB_SO_GROUP_TMNL_CHANGE_001;
	
	/**多终端流量共享群组成员移除 **/
	String SRV_ESB_SO_GROUP_TMNL_REMOVE_001 = "ESB_SO_GROUP_TMNL_REMOVE_001";
	String MN_ESB_SO_GROUP_TMNL_REMOVE_001 = ESB_URL + SRV_ESB_SO_GROUP_TMNL_REMOVE_001;

	/**个人订单校验 **/
	String SRV_ESB_SO_PERSONAL_ORDER_CHECK_003 = "ESB_SO_PERSONAL_ORDER_CHECK_003";
	String MN_ESB_SO_PERSONAL_ORDER_CHECK_003 = ESB_URL + SRV_ESB_SO_PERSONAL_ORDER_CHECK_003;
	
	/**客户不满意信息查询**/
	String SRV_SSP_QRY_DISSATISFY_CUST_SV = "SSP_QRY_DISSATISFY_CUST_SV";
	String MN_SSP_QRY_DISSATISFY_CUST_SV = ESB_URL + "queryDissatisfyCustomerByBillId";
	
	/**优选号码预判**/
	String SRV_ESB_RES_NUM_BILL_QRY_002 = "ESB_RES_NUM_BILL_QRY_002";
	String MN_ESB_RES_NUM_BILL_QRY_002 = ESB_URL + "ESB_RES_NUM_BILL_QRY_002";
	
	/**宽带账号密码查询**/
	String SRV_ESB_SO_PERSONAL_WB_QRY_003 = "ESB_SO_PERSONAL_WB_QRY_003";
	String MN_ESB_SO_PERSONAL_WB_QRY_003 = ESB_URL + "ESB_SO_PERSONAL_WB_QRY_003";
	
	/**政企发票预开申请结果查询**/
	String ESB_RES_NOTE_INVOICE_QRY_013 = "ESB_RES_NOTE_INVOICE_QRY_013";
	String MN_ESB_RES_NOTE_INVOICE_QRY_013 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRY_013";
	
	/**通票类型申请单打印发票**/
	String ESB_RES_NOTE_INVOICE_PRINT_011 = "ESB_RES_NOTE_INVOICE_PRINT_011";
	String MN_ESB_RES_NOTE_INVOICE_PRINT_011 = ESB_URL + "ESB_RES_NOTE_INVOICE_PRINT_011";
	
	/**申请单平账功能**/
	String ESB_RES_NOTE_INVOICE_INDEPENDENT_002 = "ESB_RES_NOTE_INVOICE_INDEPENDENT_002";
	String MN_ESB_RES_NOTE_INVOICE_INDEPENDENT_002 = ESB_URL + "ESB_RES_NOTE_INVOICE_INDEPENDENT_002";

	/**查询渠道信息**/
	String ESB_CHNL_CHNL_INFO_QRY_001 = "ESB_CHNL_CHNL_INFO_QRY_001";
	String MN_ESB_CHNL_CHNL_INFO_QRY_001 = ESB_URL + "ESB_CHNL_CHNL_INFO_QRY_001";
	
	/**一证五户校验查询**/
	String ESB_CS_QRY_CM_TAGCHECK_001 = "ESB_CS_QRY_CM_TAGCHECK_001";
	String MN_ESB_CS_QRY_CM_TAGCHECK_001 = ESB_URL + "ESB_CS_QRY_CM_TAGCHECK_001";
	
	/**重入网**/
	String ESB_SO_PERSONAL_GSM_REOPEN_001 = "ESB_SO_PERSONAL_GSM_REOPEN_001";
	String MN_ESB_SO_PERSONAL_GSM_REOPEN_001 = ESB_URL + "ESB_SO_PERSONAL_GSM_REOPEN_001";
	
	/**已用号码号码信息查询**/
	String ESB_RES_NUM_NUM_QRY_006 = "ESB_RES_NUM_NUM_QRY_006";
	String MN_ESB_RES_NUM_NUM_QRY_006 = ESB_URL + "ESB_RES_NUM_NUM_QRY_006";
	
	/** 牌照方配置查询 */
	String ESB_SO_PERSONAL_WB_SPQRY_001 = "ESB_SO_PERSONAL_WB_SPQRY_001";
	String MN_ESB_SO_PERSONAL_WB_SPQRY_001 = ESB_URL + "ESB_SO_PERSONAL_WB_SPQRY_001";
	
	/** 牌照方配置修改 */
	String ESB_SO_PERSONAL_WB_SPMOD_001 = "ESB_SO_PERSONAL_WB_SPMOD_001";
	String MN_ESB_SO_PERSONAL_WB_SPMOD_001 = ESB_URL + "ESB_SO_PERSONAL_WB_SPMOD_001";
	
	/** 用户流量在2，3，4G网络模式下的使用情况 */
	String ESB_CS_QRY_USED_FLOW_001 = "ESB_CS_QRY_USED_FLOW_001";
	String MN_ESB_CS_QRY_USED_FLOW_001 = ESB_URL + "ESB_CS_QRY_USED_FLOW_001";
	
	/** 群组业务拆网 */
	String ESB_SO_PERSONAL_GROUP_ORDERLOGOUT_001 = "ESB_SO_PERSONAL_GROUP_ORDERLOGOUT_001";
	String MN_ESB_SO_PERSONAL_GROUP_ORDERLOGOUT_001 = ESB_URL + "ESB_SO_PERSONAL_GROUP_ORDERLOGOUT_001";
	
	/**开具电子发票查询*/
	String ESB_RES_NOTE_INVOICE_QRY_015 = "ESB_RES_NOTE_INVOICE_QRY_015";
	String MN_ESB_RES_NOTE_INVOICE_QRY_015 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRY_015";
	
	/**电子发票开关接口*/
	String ESB_RES_NOTE_INVOICE_SWITCH_001 = "ESB_RES_NOTE_INVOICE_SWITCH_001";
	String MN_ESB_RES_NOTE_INVOICE_SWITCH_001 = ESB_URL + "ESB_RES_NOTE_INVOICE_SWITCH_001";
	
	/**纳锐人资质查询接口 */
	String ESB_RES_NOTE_INVOICE_QRY_016 = "ESB_RES_NOTE_INVOICE_QRY_016";
	String MN_ESB_RES_NOTE_INVOICE_QRY_016 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRY_016";
	
	/**电子发票查询页面的开票类型*/
	String ESB_RES_NOTE_INVOICE_QRY_017 = "ESB_RES_NOTE_INVOICE_QRY_017";
	String MN_ESB_RES_NOTE_INVOICE_QRY_017 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRY_017";
	
	/**电子发票查询页面的开票类型的关联类型*/
	String ESB_RES_NOTE_INVOICE_QRY_018 = "ESB_RES_NOTE_INVOICE_QRY_018";
	String MN_ESB_RES_NOTE_INVOICE_QRY_018 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRY_018";
	
	/**冲红原因查询*/
	String ESB_RES_NOTE_INVOICE_QRY_019 = "ESB_RES_NOTE_INVOICE_QRY_019";
	String MN_ESB_RES_NOTE_INVOICE_QRY_019 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRY_019";
	
	/**冲红办理*/
	String ESB_RES_NOTE_INVOICE_RED_001 = "ESB_RES_NOTE_INVOICE_RED_001";
	String MN_ESB_RES_NOTE_INVOICE_RED_001 = ESB_URL + "ESB_RES_NOTE_INVOICE_RED_001";
	
	/**电子发票推送*/
	String ESB_RES_NOTE_INVOICE_PUSH_001 = "ESB_RES_NOTE_INVOICE_PUSH_001";
	String MN_ESB_RES_NOTE_INVOICE_PUSH_001 = ESB_URL + "ESB_RES_NOTE_INVOICE_PUSH_001";
	
	/**电子发票开具详情查询*/
	String ESB_RES_NOTE_INVOICE_QRYDTLS_001 = "ESB_RES_NOTE_INVOICE_QRYDTLS_001";
	String MN_ESB_RES_NOTE_INVOICE_QRYDTLS_001 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRYDTLS_001";
	
	/**自定义电子发票开具*/
	String ESB_RES_NOTE_INVOICE_SEND_002 = "ESB_RES_NOTE_INVOICE_SEND_002";
	String MN_ESB_RES_NOTE_INVOICE_SEND_002 = ESB_URL + "ESB_RES_NOTE_INVOICE_SEND_002";
	
	/**账单电子发票开具*/
	String ESB_RES_NOTE_INVOICE_SEND_001 = "ESB_RES_NOTE_INVOICE_SEND_001";
	String MN_ESB_RES_NOTE_INVOICE_SEND_001 = ESB_URL + "ESB_RES_NOTE_INVOICE_SEND_001";
	
	/**充值电子发票开具和缴费*/
	String ESB_RES_NOTE_INVOICE_SEND_004 = "ESB_RES_NOTE_INVOICE_SEND_004";
	String MN_ESB_RES_NOTE_INVOICE_SEND_004 = ESB_URL + "ESB_RES_NOTE_INVOICE_SEND_004";
	
	/**一次性发票打印1,4,6*/
	String ESB_RES_NOTE_INVOICE_SEND_009 = "ESB_RES_NOTE_INVOICE_SEND_009";
	String MN_ESB_RES_NOTE_INVOICE_SEND_009 = ESB_URL + "ESB_RES_NOTE_INVOICE_SEND_009";
	
	/**报损账单电子发票打印*/
	String ESB_RES_NOTE_INVOICE_SEND_008 = "ESB_RES_NOTE_INVOICE_SEND_008";
	String MN_ESB_RES_NOTE_INVOICE_SEND_008 = ESB_URL + "ESB_RES_NOTE_INVOICE_SEND_008";

	
	/**校验待激活的实物兑换卡号*/
	String ESB_RES_PRICECARD_SALE_CHECK_001 = "ESB_RES_PRICECARD_SALE_CHECK_001";
	String MN_ESB_RES_PRICECARD_SALE_CHECK_001 = ESB_URL + "ESB_RES_PRICECARD_SALE_CHECK_001";
	
	/**实物兑换激活情况查询*/
	String ESB_RES_ENTITY_EXCHG_ACTIVE_001 = "ESB_RES_ENTITY_EXCHG_ACTIVE_001";
	String MN_ESB_RES_ENTITY_EXCHG_ACTIVE_001 = ESB_URL + "ESB_RES_ENTITY_EXCHG_ACTIVE_001";
	
	/**政企暂存资金明细查询*/
	String SRV_ESB_CS_GROUP_DEPOSIT_DTLQRY_001 = "ESB_CS_GROUP_DEPOSIT_DTLQRY_001";
	String MN_ESB_CS_GROUP_DEPOSIT_DTLQRY_001 = ESB_URL + "ESB_CS_GROUP_DEPOSIT_DTLQRY_001";
	
	/**政企暂存资金明细操作*/
	String SRV_ESB_CS_GROUP_DEPOSIT_DTLOPER_001 = "ESB_CS_GROUP_DEPOSIT_DTLOPER_001";
	String MN_ESB_CS_GROUP_DEPOSIT_DTLOPER_001 = ESB_URL + "ESB_CS_GROUP_DEPOSIT_DTLOPER_001";
	
	/**充值校验*/
	String SRV_ESB_CS_AMS_FUND_CHARGECHECK_001="ESB_CS_AMS_FUND_CHARGECHECK_001";
	String MN_ESB_CS_AMS_FUND_CHARGECHECK_001=ESB_URL+"ESB_CS_AMS_FUND_CHARGECHECK_001";

    /**个性化电子发票定制信息查询*/
    String SRV_ESB_RES_NOTE_INVOICE_QRY_025 = "ESB_RES_NOTE_INVOICE_QRY_025";
    String MN_ESB_RES_NOTE_INVOICE_QRY_025 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRY_025";

    /**个性化电子发票月账单定制*/
    String SRV_ESB_RES_NOTE_INVOICE_PUSH_003 = "ESB_RES_NOTE_INVOICE_PUSH_003";
    String MN_ESB_RES_NOTE_INVOICE_PUSH_003 = ESB_URL + "ESB_RES_NOTE_INVOICE_PUSH_003";
    
    /**上网日志详情查询*/
	String SRV_ESB_CS_QRY_RECORD_ONLINELOG_001 = "ESB_CS_QRY_RECORD_ONLINELOG_001";
	String MN_ESB_CS_QRY_RECORD_ONLINELOG_001 = ESB_URL + "ESB_CS_QRY_RECORD_ONLINELOG_001";
	
	/**上网日志APP详情查询*/
	String SRV_ESB_CS_QRY_RECORD_TOPN_001 = "ESB_CS_QRY_RECORD_TOPN_001";
	String MN_ESB_CS_QRY_RECORD_TOPN_001 = ESB_URL + "ESB_CS_QRY_RECORD_TOPN_001";
	
	/**计费详单流量查询*/
	String SRV_ESB_CS_QRY_RECORD_FLOWDETAIL_001 = "ESB_CS_QRY_RECORD_FLOWDETAIL_001";
	String MN_ESB_CS_QRY_RECORD_FLOWDETAIL_001 = ESB_URL + "ESB_CS_QRY_RECORD_FLOWDETAIL_001";
	
	/**DPI流量查询*/
	String SRV_ESB_CS_QRY_RECORD_FLOW_001 = "ESB_CS_QRY_RECORD_FLOW_001";
	String MN_ESB_CS_QRY_RECORD_FLOW_001 = ESB_URL + "ESB_CS_QRY_RECORD_FLOW_001";
	
	/**财务开票申请记录查询*/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_029 = "ESB_RES_NOTE_INVOICE_QRY_029";
	String MN_ESB_RES_NOTE_INVOICE_QRY_029 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRY_029";
	
	/**财务开票申请记录发票信息查询*/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_030 = "ESB_RES_NOTE_INVOICE_QRY_030";
	String MN_ESB_RES_NOTE_INVOICE_QRY_030 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRY_030";
	
	/**财务开票申请*/
	String SRV_ESB_RES_NOTE_INVOICE_SEND_013 = "ESB_RES_NOTE_INVOICE_SEND_013";
	String MN_ESB_RES_NOTE_INVOICE_SEND_013 = ESB_URL + "ESB_RES_NOTE_INVOICE_SEND_013";
	
	/**财务开票申请单全量开票*/  
	String SRV_ESB_RES_NOTE_INVOICE_SEND_015 = "ESB_RES_NOTE_INVOICE_SEND_015";
	String MN_ESB_RES_NOTE_INVOICE_SEND_015 = ESB_URL + "ESB_RES_NOTE_INVOICE_SEND_015";
	
	/**财务开票查看当前审批进度信息*/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_026 = "ESB_RES_NOTE_INVOICE_QRY_026";
	String MN_ESB_RES_NOTE_INVOICE_QRY_026 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRY_026";
	
	/**财务开票查看当前审批人信息*/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_027 = "ESB_RES_NOTE_INVOICE_QRY_027";
	String MN_ESB_RES_NOTE_INVOICE_QRY_027 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRY_027";
	
	/**财务开票撤销申请工单*/
	String SRV_ESB_RES_NOTE_INVOICE_SEND_014 = "ESB_RES_NOTE_INVOICE_SEND_014";
	String MN_ESB_RES_NOTE_INVOICE_SEND_014 = ESB_URL + "ESB_RES_NOTE_INVOICE_SEND_014";
	
	/**财务开票多选票据记录申请冲红*/
	String SRV_ESB_RES_NOTE_INVOICE_SEND_016 = "ESB_RES_NOTE_INVOICE_SEND_016";
	String MN_ESB_RES_NOTE_INVOICE_SEND_016 = ESB_URL + "ESB_RES_NOTE_INVOICE_SEND_016";
	
	/**财务开票申请审批人信息校验*/
	String SRV_ESB_RES_NOTE_INVOICE_SEND_017 = "ESB_RES_NOTE_INVOICE_SEND_017";
	String MN_ESB_RES_NOTE_INVOICE_SEND_017 = ESB_URL + "ESB_RES_NOTE_INVOICE_SEND_017";

	/**流量直充业务详情查询*/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_038 = "ESB_RES_NOTE_INVOICE_QRY_038";
	String MN_ESB_RES_NOTE_INVOICE_QRY_038 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRY_038";
	
	/**流量直充业务发票打印*/
	String SRV_ESB_RES_NOTE_INVOICE_SEND_022 = "ESB_RES_NOTE_INVOICE_SEND_022";
	String MN_ESB_RES_NOTE_INVOICE_SEND_022 = ESB_URL + "ESB_RES_NOTE_INVOICE_SEND_022";
	
	//addby xulq2 2016-06-29
	/**调用接口传送身份信息入实名库保存*/
	String SRV_ESB_SO_PERSONAL_ORDER_REALSAVE_001 = "ESB_SO_PERSONAL_ORDER_REALSAVE_001";
	String MN_ESB_SO_PERSONAL_ORDER_REALSAVE_001 = ESB_URL + "ESB_SO_PERSONAL_ORDER_REALSAVE_001";
	
	//addby xulq2 2016-06-29
	/**调用实名库校验用户信息是否为实名*/
	String SRV_ESB_SO_PERSONAL_ORDER_REALQRY_001 = "ESB_SO_PERSONAL_ORDER_REALQRY_001";
	String MN_ESB_SO_PERSONAL_ORDER_REALQRY_001 = ESB_URL + "ESB_SO_PERSONAL_ORDER_REALQRY_001";
	
	/**实名库信息维护,根据证件号码客户名称维护实名库比对库信息added by huazie 2016-10-28*/
	String SRV_ESB_SO_PERSONAL_ORDER_POLICECHECK_001 = "ESB_SO_PERSONAL_ORDER_POLICECHECK_001";
	String MN_ESB_SO_PERSONAL_ORDER_POLICECHECK_001 =ESB_URL + "ESB_SO_PERSONAL_ORDER_POLICECHECK_001";

	/**实名库比对库信息查询,根据证件号码查询实名库比对库信息added by huazie 2016-10-28*/
	String SRV_ESB_SO_PERSONAL_ORDER_REALEDIT_001 = "ESB_SO_PERSONAL_ORDER_REALEDIT_001";
	String MN_ESB_SO_PERSONAL_ORDER_REALEDIT_001 = ESB_URL + "ESB_SO_PERSONAL_ORDER_REALEDIT_001";
	
	//addby huazie 2016-10-28
	/**实名库比对库信息查询,根据证件号码查询实名库比对库信息*/
	String SRV_ESB_SO_PERSONAL_ORDER_REALQRY_002 = "ESB_SO_PERSONAL_ORDER_REALQRY_002";
	String MN_ESB_SO_PERSONAL_ORDER_REALQRY_002 = ESB_URL + "ESB_SO_PERSONAL_ORDER_REALQRY_002";
	
	/**电子发票对账查询接口*/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_031 = "ESB_RES_NOTE_INVOICE_QRY_031";
	String MN_ESB_RES_NOTE_INVOICE_QRY_031 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRY_031";
	
	/**电子发票对账明细查询接口*/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_032 = "ESB_RES_NOTE_INVOICE_QRY_032";
	String MN_ESB_RES_NOTE_INVOICE_QRY_032 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRY_032";
	
	/**电子发票对账结果处理*/
	String SRV_ESB_RES_NOTE_INVOICE_SEND_018 = "ESB_RES_NOTE_INVOICE_SEND_018";
	String MN_ESB_RES_NOTE_INVOICE_SEND_018 = ESB_URL + "ESB_RES_NOTE_INVOICE_SEND_018";
	
	/**政企电子发票查询接口*/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_033 = "ESB_RES_NOTE_INVOICE_QRY_033";
	String MN_ESB_RES_NOTE_INVOICE_QRY_033 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRY_033";
	
	/**政企电子发票打印/下载 验证码查询接口*/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_034 = "ESB_RES_NOTE_INVOICE_QRY_034";
	String MN_ESB_RES_NOTE_INVOICE_QRY_034 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRY_034";
	
	/**政企电子发票打印/下载 验证码校验接口*/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_035 = "ESB_RES_NOTE_INVOICE_QRY_035";
	String MN_ESB_RES_NOTE_INVOICE_QRY_035 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRY_035";
	
	/**政企电子发票推送联系人邮箱查询接口*/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_036 = "ESB_RES_NOTE_INVOICE_QRY_036";
	String MN_ESB_RES_NOTE_INVOICE_QRY_036 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRY_036";
	
	/**政企电子发票批量推送接口*/
	String SRV_ESB_RES_NOTE_INVOICE_SEND_020 = "ESB_RES_NOTE_INVOICE_SEND_020";
	String MN_ESB_RES_NOTE_INVOICE_SEND_020 = ESB_URL + "ESB_RES_NOTE_INVOICE_SEND_020";
	
	/**政企电子发票打印/下载 验证码下发接口*/
	String SRV_ESB_RES_NOTE_INVOICE_SEND_021 = "ESB_RES_NOTE_INVOICE_SEND_021";
	String MN_ESB_RES_NOTE_INVOICE_SEND_021 = ESB_URL + "ESB_RES_NOTE_INVOICE_SEND_021";
	/**SIM卡校验和修复*/
	String SRV_ESB_RES_SIM_SIM_REPAIR_001="ESB_RES_SIM_SIM_REPAIR_001";
	String MN_ESB_RES_SIM_SIM_REPAIR_001=ESB_URL+"ESB_RES_SIM_SIM_REPAIR_001";
	/**非实名销户资金转移*/
	String SRV_ESB_CS_AMS_FUND_NRBALANCETRANS_001="ESB_CS_AMS_FUND_NRBALANCETRANS_001";
	String MN_ESB_CS_AMS_FUND_NRBALANCETRANS_001=ESB_URL+"ESB_CS_AMS_FUND_NRBALANCETRANS_001";
	/**非实名销户资金处理记录查询*/
	String SRV_ESB_CS_QRY_AMS_NRBALREFUNDQRY_001 ="ESB_CS_QRY_AMS_NRBALREFUNDQRY_001";
	String MN_ESB_CS_QRY_AMS_NRBALREFUNDQRY_001 = ESB_URL+"ESB_CS_QRY_AMS_NRBALREFUNDQRY_001";
	/**未读公告数量*/
	String SRV_ESB_CHNL_CHNL_INFO_NOTICELIST_001 = "ESB_CHNL_CHNL_INFO_NOTICELIST_001";
	String MN_ESB_CHNL_CHNL_INFO_NOTICELIST_001 = "http://esb-sc.yw.zj.chinamobile.com;"+"ESB_CHNL_CHNL_INFO_NOTICELIST_001";

  
	/**查询电子发票存量 */
	String SRV_ESB_RES_NOTE_INVOICE_QRY_039 = "ESB_RES_NOTE_INVOICE_QRY_039";
	String MN_ESB_RES_NOTE_INVOICE_QRY_039 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRY_039";
	
	/**电子发票开票详情统计查询 */
	String SRV_ESB_RES_NOTE_INVOICE_QRY_040 = "ESB_RES_NOTE_INVOICE_QRY_040";
	String MN_ESB_RES_NOTE_INVOICE_QRY_040 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRY_040";
	
	/**电子发票开票统计查询 */
	String SRV_ESB_RES_NOTE_INVOICE_QRY_041 = "ESB_RES_NOTE_INVOICE_QRY_041";
	String MN_ESB_RES_NOTE_INVOICE_QRY_041 = ESB_URL + "ESB_RES_NOTE_INVOICE_QRY_041";
	
	/**固话套餐变更*/
	String SRV_ESB_SO_PERSONAL_FIXNUM_CHANGE_001="ESB_SO_PERSONAL_FIXNUM_CHANGE_001";
	String MN_ESB_SO_PERSONAL_FIXNUM_CHANGE_001=ESB_URL+"ESB_SO_PERSONAL_FIXNUM_CHANGE_001";
	/**三户信息查询新接口*/
	String SRV_ESB_CS_QRY_MULTI_ALLCMUSERACCTQRY_001="ESB_CS_QRY_MULTI_ALLCMUSERACCTQRY_001";
	String MN_ESB_CS_QRY_MULTI_ALLCMUSERACCTQRY_001=ESB_URL+"ESB_CS_QRY_MULTI_ALLCMUSERACCTQRY_001";
	/**固话增值业务变更  */
	String SRV_ESB_SO_PERSONAL_FIXNUM_CHANGE_002="ESB_SO_PERSONAL_FIXNUM_CHANGE_002";
	String MN_ESB_SO_PERSONAL_FIXNUM_CHANGE_002=ESB_URL+"ESB_SO_PERSONAL_FIXNUM_CHANGE_002";
	
	/**暂存款待办工单数*/
	String SRV_ESB_SO_GROUP_FUND_ORDERQRY_001="ESB_SO_GROUP_FUND_ORDERQRY_001";
	String MN_ESB_SO_GROUP_FUND_ORDERQRY_001=ESB_URL+"ESB_SO_GROUP_FUND_ORDERQRY_001";
	
	/**证件综合信息查询added by huazie 2016-11-28*/
	String SRV_ESB_CS_QRY_CM_CERTSYNINFOQRY_001 = "ESB_CS_QRY_CM_CERTSYNINFOQRY_001";
	String MN_ESB_CS_QRY_CM_CERTSYNINFOQRY_001 = ESB_URL + "ESB_CS_QRY_CM_CERTSYNINFOQRY_001";
	

	/**人脸识别信息保存*/
	String SRV_ESB_CM_CM_CM_FACESAVE_001  = "ESB_CM_CM_CM_FACESAVE_001";
	String MN_ESB_CM_CM_CM_FACESAVE_001 =ESB_URL+"ESB_CM_CM_CM_FACESAVE_001";
	/**人脸识别校验结果查询*/
	String SRV_ESB_CM_CM_CM_FACEQRY_001  = "ESB_CM_CM_CM_FACEQRY_001";
	String MN_ESB_CM_CM_CM_FACEQRY_001 = ESB_URL+"ESB_CM_CM_CM_FACEQRY_001";


	/**流量直冲发票批量开具*/
	String SRV_ESB_RES_NOTE_INVOICE_SEND_023 ="ESB_RES_NOTE_INVOICE_SEND_023";
	String MN_ESB_RES_NOTE_INVOICE_SEND_023 = ESB_URL+"ESB_RES_NOTE_INVOICE_SEND_023";
	
	/**账单发票批量开具*/
	String SRV_ESB_RES_NOTE_INVOICE_SEND_024 ="ESB_RES_NOTE_INVOICE_SEND_024";
	String MN_ESB_RES_NOTE_INVOICE_SEND_024 = ESB_URL+"ESB_RES_NOTE_INVOICE_SEND_024";
	
	/**查询推送信息*/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_042 ="ESB_RES_NOTE_INVOICE_QRY_042";
	String MN_ESB_RES_NOTE_INVOICE_QRY_042 = ESB_URL+"ESB_RES_NOTE_INVOICE_QRY_042";
	
	/**身份证、户口簿实名库、公安比对 记@author chenhanwei */
    String SRV_ESB_SO_PERSONAL_ORDER_POLICECHECK_002 = "ESB_SO_PERSONAL_ORDER_POLICECHECK_002";
    String MN_ESB_SO_PERSONAL_ORDER_POLICECHECK_002 = ESB_URL+SRV_ESB_SO_PERSONAL_ORDER_POLICECHECK_002;
    
    /**人脸识别 @author chenhanwei */
    String SRV_ESB_CM_CM_CM_FACECHK_001 = "ESB_CM_CM_CM_FACECHK_001";
    String MN_ESB_CM_CM_CM_FACECHK_001 = ESB_URL+SRV_ESB_CM_CM_CM_FACECHK_001;

   
    /**根据集团计费号和地市查询宽带（专线）信息*/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_045 = "ESB_RES_NOTE_INVOICE_QRY_045";
	String MN_ESB_RES_NOTE_INVOICE_QRY_045 = ESB_URL+SRV_ESB_RES_NOTE_INVOICE_QRY_045;
	
	 /**根据账期查询预开发票报表*/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_046 = "ESB_RES_NOTE_INVOICE_QRY_046";
	String MN_ESB_RES_NOTE_INVOICE_QRY_046 = ESB_URL+SRV_ESB_RES_NOTE_INVOICE_QRY_046;
	
	/**根据集团计费号查询订购信息*/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_044 ="ESB_RES_NOTE_INVOICE_QRY_044";
	String MN_ESB_RES_NOTE_INVOICE_QRY_044 = ESB_URL+"ESB_RES_NOTE_INVOICE_QRY_044";
	
	/**专线预开发票申请*/
	String SRV_ESB_RES_NOTE_INVOICE_PRINT_013 ="ESB_RES_NOTE_INVOICE_PRINT_013";
	String MN_ESB_RES_NOTE_INVOICE_PRINT_013 = ESB_URL+"ESB_RES_NOTE_INVOICE_PRINT_013";

	/**开具电子发票*/
	String SRV_ESB_RES_NOTE_INVOICE_SEND_025 ="ESB_RES_NOTE_INVOICE_SEND_025";
	String MN_ESB_RES_NOTE_INVOICE_SEND_025 = ESB_URL+"ESB_RES_NOTE_INVOICE_SEND_025";
	
	/**国漫预受理*/
	String SRV_ESB_SO_PERSONAL_ORDER_GM_001="ESB_SO_PERSONAL_ORDER_GM_001";
	String MN_ESB_SO_PERSONAL_ORDER_GM_001=ESB_URL+"ESB_SO_PERSONAL_ORDER_GM_001";
	
	/**国漫业务预受理记录查询接口*/
	String SRV_ESB_SO_PERSONAL_ORDER_GMQRY_002="ESB_SO_PERSONAL_ORDER_GMQRY_002";
	String MN_ESB_SO_PERSONAL_ORDER_GMQRY_002=ESB_URL+"ESB_SO_PERSONAL_ORDER_GMQRY_002";
	
	/**国漫用户已订购策划查询*/
	String SRV_ESB_SO_PERSONAL_ORDER_GMQRY_001="ESB_SO_PERSONAL_ORDER_GMQRY_001";
	String MN_ESB_SO_PERSONAL_ORDER_GMQRY_001=ESB_URL+"ESB_SO_PERSONAL_ORDER_GMQRY_001";
	
	/**集中考核管理信息查询*/
	String SRV_ESB_CHNL_CHNL_INFO_KPICHKQRY_001="ESB_CHNL_CHNL_INFO_KPICHKQRY_001";
	String MN_ESB_CHNL_CHNL_INFO_KPICHKQRY_001=ESB_URL+"ESB_CHNL_CHNL_INFO_KPICHKQRY_001";
	
	/**一证五户信息查询**/
	String SRV_ESB_CS_QRY_CM_CERTPHONEINFOQRY_001="ESB_CS_QRY_CM_CERTPHONEINFOQRY_001";
	String MN_ESB_CS_QRY_CM_CERTPHONEINFOQRY_001=ESB_URL+"ESB_CS_QRY_CM_CERTPHONEINFOQRY_001";
	
	/**内容管理平台下载*/
	String SRV_ESB_BASE_CMS_FILE_DOWNLOAD_001="ESB_BASE_CMS_FILE_DOWNLOAD_001";
	String MN_ESB_BASE_CMS_FILE_DOWNLOAD_001=ESB_URL+"execute";
	
	/**个人实名库维护日志查询接口*/
	String SRV_ESB_CS_QRY_CM_REALHISQRY_001="ESB_CS_QRY_CM_REALHISQRY_001";
	String MN_ESB_CS_QRY_CM_REALHISQRY_001=ESB_URL+"ESB_CS_QRY_CM_REALHISQRY_001";
	
	/**个人实名库信息维护接口*/
	String SRV_ESB_SO_PERSONAL_ORDER_REALEDIT_002="ESB_SO_PERSONAL_ORDER_REALEDIT_002";
	String MN_ESB_SO_PERSONAL_ORDER_REALEDIT_002=ESB_URL+"ESB_SO_PERSONAL_ORDER_REALEDIT_002";

	/**滞纳金查询接口 */
	String SRV_ESB_RES_NOTE_INVOICE_QRY_047="ESB_RES_NOTE_INVOICE_QRY_047";
	String MN_ESB_RES_NOTE_INVOICE_QRY_047=ESB_URL+"ESB_RES_NOTE_INVOICE_QRY_047";
	
	/** 宽带以及宽带电视的查询关系 **/
	String SRV_ESB_SO_PERSONAL_WB_QRY_013 = "ESB_SO_PERSONAL_WB_QRY_013";
	String MN_ESB_SO_PERSONAL_WB_QRY_013 = ESB_URL+SRV_ESB_SO_PERSONAL_WB_QRY_013;
	
	/**宽带以及宽带电视的关联关系  **/
	String SRV_ESB_SO_PERSONAL_WB_QRY_012 = "ESB_SO_PERSONAL_WB_QRY_012";
	String MN_ESB_SO_PERSONAL_WB_QRY_012 = ESB_URL+SRV_ESB_SO_PERSONAL_WB_QRY_012;
	
	/**一证五号预占信息查询  **/
	String SRV_ESB_CS_QRY_CM_CERTCAMPONQRY_001 = "ESB_CS_QRY_CM_CERTCAMPONQRY_001";
	String MN_ESB_CS_QRY_CM_CERTCAMPONQRY_001 = ESB_URL+"ESB_CS_QRY_CM_CERTCAMPONQRY_001";
	
	/**解除一证五号预占  **/
	String SRV_ESB_SO_PERSONAL_ORDER_CERTCAMPON_001 = "ESB_SO_PERSONAL_ORDER_CERTCAMPON_001";
	String MN_ESB_SO_PERSONAL_ORDER_CERTCAMPON_001 = ESB_URL+"ESB_SO_PERSONAL_ORDER_CERTCAMPON_001";
	
	/**查询前店后厂业务意向单  **/
	String SRV_ESB_SO_PERSONAL_PROM_QRY_004 = "ESB_SO_PERSONAL_PROM_QRY_004";
	String MN_ESB_SO_PERSONAL_PROM_QRY_004 = ESB_URL+"ESB_SO_PERSONAL_PROM_QRY_004";

	/**提交前店后厂业务订单  **/
	String SRV_ESB_SO_PERSONAL_PROM_ORDER_003 = "ESB_SO_PERSONAL_PROM_ORDER_003";
	String MN_ESB_SO_PERSONAL_PROM_ORDER_003 = ESB_URL+"ESB_SO_PERSONAL_PROM_ORDER_003";

	/**校验一证五户信息  **/
	String SRV_ESB_CS_QRY_CM_POLICEYZDMQRY_001 = "ESB_CS_QRY_CM_POLICEYZDMQRY_001";
	String MN_ESB_CS_QRY_CM_POLICEYZDMQRY_001 = ESB_URL+"ESB_CS_QRY_CM_POLICEYZDMQRY_001";
	
	/**查询与操作流量账户的功能**/
	String SRV_ESB_CS_AMS_FM_ACCTDEAL_001 = "ESB_CS_AMS_FM_ACCTDEAL_001";
	String MN_ESB_CS_AMS_FM_ACCTDEAL_001 = ESB_URL+"ESB_CS_AMS_FM_ACCTDEAL_001";
	
	/**充值缴费电子发票合并开具**/
	String SRV_ESB_RES_NOTE_INVOICE_SEND_026 = "ESB_RES_NOTE_INVOICE_SEND_026";
	String MN_ESB_RES_NOTE_INVOICE_SEND_026 = ESB_URL + "ESB_RES_NOTE_INVOICE_SEND_026";
	
	/**发票开具情况监控表查询  **/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_048 = "ESB_RES_NOTE_INVOICE_QRY_048";
	String MN_ESB_RES_NOTE_INVOICE_QRY_048 = ESB_URL+"ESB_RES_NOTE_INVOICE_QRY_048";
	
	/**定向视频用户已订购查询接口**/
	String SRV_ESB_SO_PERSONAL_APP_QRY_001 = "ESB_SO_PERSONAL_APP_QRY_001";
	String MN_ESB_SO_PERSONAL_APP_QRY_001  = ESB_URL+"ESB_SO_PERSONAL_APP_QRY_001";
	/**定向视频订购退订修改接口**/
	String SRV_ESB_SO_PERSONAL_APP_DEAL_001 = "ESB_SO_PERSONAL_APP_DEAL_001";
	String MN_ESB_SO_PERSONAL_APP_DEAL_001 = ESB_URL+"ESB_SO_PERSONAL_APP_DEAL_001";
	
	/**跨区补卡受理信息查询接口**/
	String SRV_ESB_CS_SC_SC_INTERPROVINCIALQRY_001 = "ESB_CS_SC_SC_INTERPROVINCIALQRY_001";
	String MN_ESB_CS_SC_SC_INTERPROVINCIALQRY_001 = ESB_URL+"ESB_CS_SC_SC_INTERPROVINCIALQRY_001";
	
	/***查询安心小号**/
	String SRV_ESB_CS_QRY_CM_CERTPHONEINFOQRY_002 = "ESB_CS_QRY_CM_CERTPHONEINFOQRY_002";
	String MN_ESB_CS_QRY_CM_CERTPHONEINFOQRY_002 = ESB_URL+"ESB_CS_QRY_CM_CERTPHONEINFOQRY_002";
	
	/***人脸识别需要补拍的记录查询**/
	String SRV_ESB_CM_CM_CM_FACEQRY_002 = "ESB_CM_CM_CM_FACEQRY_002";
	String MN_ESB_CM_CM_CM_FACEQRY_002 = ESB_URL+"ESB_CM_CM_CM_FACEQRY_002";
	
	/***查询证件下的使用人数量**/
	String SRV_ESB_CS_QRY_CM_CERTUSERNUM_001 = "ESB_CS_QRY_CM_CERTUSERNUM_001";
	String MN_ESB_CS_QRY_CM_CERTUSERNUM_001 = ESB_URL+"ESB_CS_QRY_CM_CERTUSERNUM_001";
	
	/***流量分享卡主卡绑定校验接口**/
	String SRV_ESB_SO_PERSONAL_ORDER_FSCCHECK_001 = "ESB_SO_PERSONAL_ORDER_FSCCHECK_001";
	String MN_ESB_SO_PERSONAL_ORDER_FSCCHECK_001 = ESB_URL+"ESB_SO_PERSONAL_ORDER_FSCCHECK_001";
	
	/***流量分享卡绑定和解绑接口**/
	String SRV_ESB_SO_PERSONAL_ORDER_FSCDEAL_001 = "ESB_SO_PERSONAL_ORDER_FSCDEAL_001";
	String MN_ESB_SO_PERSONAL_ORDER_FSCDEAL_001 = ESB_URL+"ESB_SO_PERSONAL_ORDER_FSCDEAL_001";
	
	/***流量分享卡查询接口**/
	String SRV_ESB_SO_PERSONAL_ORDER_FSCRELQRY_001 = "ESB_SO_PERSONAL_ORDER_FSCRELQRY_001";
	String MN_ESB_SO_PERSONAL_ORDER_FSCRELQRY_001 = ESB_URL+"ESB_SO_PERSONAL_ORDER_FSCRELQRY_001";
	
		/***一号多终端主卡绑定校验接口**/
	String SRV_ESB_SO_GROUP_TMNL_CHECK_001 = "ESB_SO_GROUP_TMNL_CHECK_001";
	String MN_ESB_SO_GROUP_TMNL_CHECK_001 = ESB_URL+"ESB_SO_GROUP_TMNL_CHECK_001";	
	
		/***一号多终端查询接口**/
	String SRV_ESB_SO_GROUP_TMNL_QRY_003 = "ESB_SO_GROUP_TMNL_QRY_003";
	String MN_ESB_SO_GROUP_TMNL_QRY_003 = ESB_URL+"ESB_SO_GROUP_TMNL_QRY_003";	
	
		/***一号多终端组网接口**/
	String SRV_ESB_SO_GROUP_TMNL_CREATE_002 = "ESB_SO_GROUP_TMNL_CREATE_002";
	String MN_ESB_SO_GROUP_TMNL_CREATE_002 = ESB_URL+"ESB_SO_GROUP_TMNL_CREATE_002";	
	
		/***一号多终端添加删除成员接口**/
	String SRV_ESB_SO_GROUP_TMNL_CHANGE_002 = "ESB_SO_GROUP_TMNL_CHANGE_002";
	String MN_ESB_SO_GROUP_TMNL_CHANGE_002 = ESB_URL+"ESB_SO_GROUP_TMNL_CHANGE_002";	
		/***一号多终端暂停恢复接口**/
	String SRV_ESB_SO_GROUP_TMNL_OPER_001 = "ESB_SO_GROUP_TMNL_OPER_001";
	String MN_ESB_SO_GROUP_TMNL_OPER_001 = ESB_URL+"ESB_SO_GROUP_TMNL_OPER_001";	
		/***一号多终端拆网接口**/
	String SRV_ESB_SO_GROUP_TMNL_QUIT_001 = "ESB_SO_GROUP_TMNL_QUIT_001";
	String MN_ESB_SO_GROUP_TMNL_QUIT_001 = ESB_URL+"ESB_SO_GROUP_TMNL_QUIT_001";	
	
	/***流量监控鉴权接口**/
	String SRV_ESB_CS_DETAIL_LIST_VERIFY_SV = "ESB_CS_DETAIL_LIST_VERIFY_SV";
	String MN_ESB_CS_DETAIL_LIST_VERIFY_SV = "http://zj.soap.asiainfo.com;"+"submitApproveProcess4ESB";

	String SRV_ESB_CS_QRY_CM_CERTPHONEINFOQRY_003 = "ESB_CS_QRY_CM_CERTPHONEINFOQRY_003";
	String MN_ESB_CS_QRY_CM_CERTPHONEINFOQRY_003 = ESB_URL+"ESB_CS_QRY_CM_CERTPHONEINFOQRY_003";
	
	String SRV_ESB_RES_NOTE_INVOICE_SEND_027 = "ESB_RES_NOTE_INVOICE_SEND_027";
	String MN_ESB_RES_NOTE_INVOICE_SEND_027 = ESB_URL+"ESB_RES_NOTE_INVOICE_SEND_027";
	
	/***报表导出工单查询**/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_051 = "ESB_RES_NOTE_INVOICE_QRY_051";
	String MN_ESB_RES_NOTE_INVOICE_QRY_051 = ESB_URL+"ESB_RES_NOTE_INVOICE_QRY_051";
	
	/** 集团账单电子发票推送定制信息查询 */
	String SRV_ESB_RES_NOTE_INVOICE_QRY_050 = "ESB_RES_NOTE_INVOICE_QRY_050";
	String MN_ESB_RES_NOTE_INVOICE_QRY_050 = ESB_URL+"ESB_RES_NOTE_INVOICE_QRY_050";
	
	/**  发票资金池余额明细查询 */
	String SRV_ESB_RES_NOTE_INVOICE_QRY_053 = "ESB_RES_NOTE_INVOICE_QRY_053";
	String MN_ESB_RES_NOTE_INVOICE_QRY_053 = ESB_URL+"ESB_RES_NOTE_INVOICE_QRY_053";
	
	/**集团账单电子发票推送定制*/
	String SRV_ESB_RES_NOTE_INVOICE_PUSH_004 = "ESB_RES_NOTE_INVOICE_PUSH_004";
	String MN_ESB_RES_NOTE_INVOICE_PUSH_004 = ESB_URL+"ESB_RES_NOTE_INVOICE_PUSH_004";
	
	/**
	 * 集团账户信息查询
	 */
	String SRV_ESB_CS_QRY_MULTI_GRPACCTDTLQRY_001 = "ESB_CS_QRY_MULTI_GRPACCTDTLQRY_001";
	String MN_ESB_CS_QRY_MULTI_GRPACCTDTLQRY_001= ESB_URL+"ESB_CS_QRY_MULTI_GRPACCTDTLQRY_001";
	/**
	 * 下发采集验证工单受理接口
	 * **/
	String SRV_ESB_SO_PERSONAL_ORDER_SENDBILL_001 = "ESB_SO_PERSONAL_ORDER_SENDBILL_001";
	String MN_ESB_SO_PERSONAL_ORDER_SENDBILL_001 = ESB_URL+"ESB_SO_PERSONAL_ORDER_SENDBILL_001";
	/**
	 * 电子发票/专票票面：销方银行账号信息按开票员获取配置信息查询
	 * **/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_055 = "ESB_RES_NOTE_INVOICE_QRY_055";
	String MN_ESB_RES_NOTE_INVOICE_QRY_055 = ESB_URL+"ESB_RES_NOTE_INVOICE_QRY_055";
	/**
	 * 电子发票、专票票面：销方银行账号信息按开票员获取配置信息设置
	 * **/
	String SRV_ESB_RES_NOTE_INVOICE_SEND_029 = "ESB_RES_NOTE_INVOICE_SEND_029";
	String MN_ESB_RES_NOTE_INVOICE_SEND_029 = ESB_URL+"ESB_RES_NOTE_INVOICE_SEND_029";
	
	/**
	 * 纳税人资质在线数据查询
	 * **/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_054 = "ESB_RES_NOTE_INVOICE_QRY_054";
	String MN_ESB_RES_NOTE_INVOICE_QRY_054 = ESB_URL+"ESB_RES_NOTE_INVOICE_QRY_054";
	
	/**
	 * CRM存量资质与在线资质信息比对结果查询
	 * **/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_056 = "ESB_RES_NOTE_INVOICE_QRY_056";
	String MN_ESB_RES_NOTE_INVOICE_QRY_056 = ESB_URL+"ESB_RES_NOTE_INVOICE_QRY_056";

	/**
	 * 在线纳税人资质同步
	 * **/
	String SRV_ESB_RES_NOTE_INVOICE_SEND_028 = "ESB_RES_NOTE_INVOICE_SEND_028";
	String MN_ESB_RES_NOTE_INVOICE_SEND_028 = ESB_URL+"ESB_RES_NOTE_INVOICE_SEND_028";
	
	/**
	 * CRM存量资质与在线资质信息比对结果查询
	 * **/
	String SRV_ESB_RES_NOTE_INVOICE_QRY_057 = "ESB_RES_NOTE_INVOICE_QRY_057";
	String MN_ESB_RES_NOTE_INVOICE_QRY_057 = ESB_URL+"ESB_RES_NOTE_INVOICE_QRY_057";
	
	/**长市漫割接数据查询接口**/
    String SRV_ESB_SO_PERSONAL_VAS_QRY_001 ="ESB_SO_PERSONAL_VAS_QRY_001";
    String MN_ESB_SO_PERSONAL_VAS_QRY_001 =ESB_URL+SRV_ESB_SO_PERSONAL_VAS_QRY_001;
    
    /**
	 * 应用在各日期和小时分布情况（4003）
	 * **/
	String SRV_ESB_CS_QRY_RECORD_FLOW_002 = "ESB_CS_QRY_RECORD_FLOW_002";
	String MN_ESB_CS_QRY_RECORD_FLOW_002 = ESB_URL+"ESB_CS_QRY_RECORD_FLOW_002";
}
